--add vista
(SELECT id as idtipo_visita, description as motivo, order as ordine, enabled, description_en as motivo_en, color, theme, theme_id, theme_en
 FROM simfito.tipologiasito)
union
(SELECT idtipo_visita+1000000000, motivo, ordine, false, motivo_en, null, null, null, null
 FROM simfito.tipo_visita_0)
ORDER BY idtipo_visita;

update simfito.scheda set idtipo_visita=1000000000+idtipo_visita;

--TIPOLOGOE CONTROLLATE
    --creazione
CREATE TABLE simfito.tipologiacontrollata
(
  id serial NOT NULL,
  descrizione character varying NOT NULL,
  ordinamento integer NOT NULL,
  descrizione_en character varying,
  CONSTRAINT tipologicontrollata_pkey PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE simfito.tipologiacontrollata
  OWNER TO postgres;

    --popolamento
INSERT INTO simfito.tipologiacontrollata (descrizione, descrizione_en, ordinamento)
VALUES ('Talee','Talee',0),
    ('Frutti','Frutti',1),
    ('Pianta','Pianta',2),
    ('Pianta in vivaio','Pianta in vivaio',3),
    ('Patate da seme','Patate da seme',4),
    ('Semi','Semi',5),
    ('Terreno','Terreno',6),
    ('Patate da consumo','Patate da consumo',7),
    ('Imballaggi in legno','Imballaggi in legno',8),
    ('Legno', 'Legno', 9),
    ('Legname', 'Legname',10),
    ('Altro (specificare obbligatoriamente)','Altro (specificare obbligatoriamente)',999)

--Modifica della tabella delle osservazioni
ALTER TABLE simfito.osservazioni ADD COLUMN unita integer DEFAULT 0;
ALTER TABLE simfito.osservazioni ADD COLUMN unita_chk integer DEFAULT 0;
ALTER TABLE simfito.osservazioni ADD COLUMN peso real DEFAULT 0;
ALTER TABLE simfito.osservazioni ADD COLUMN peso_chk real DEFAULT 0;
ALTER TABLE simfito.osservazioni ADD COLUMN lotti integer DEFAULT 0;
ALTER TABLE simfito.osservazioni ADD COLUMN lotti_chk integer DEFAULT 0;
ALTER TABLE simfito.osservazioni ADD COLUMN lotti_camp integer DEFAULT 0;
ALTER TABLE simfito.osservazioni ADD COLUMN tipologiacontrollata_id integer;
ALTER TABLE simfito.osservazioni ADD COLUMN provenienza VARCHAR DEFAULT 'Italia'

--aggiunta tabella degli stati
CREATE TABLE IF NOT EXISTS simfito.stati (
  id_stati serial NOT NULL,
  nome_stati varchar(128) DEFAULT NULL,
  sigla_numerica_stati varchar(4) DEFAULT NULL,
  sigla_iso_3166_1_alpha_3_stati varchar(3) DEFAULT NULL,
  sigla_iso_3166_1_alpha_2_stati varchar(2) DEFAULT NULL,
  PRIMARY KEY (id_stati)
);

INSERT INTO simfito.stati (id_stati, nome_stati, sigla_numerica_stati, sigla_iso_3166_1_alpha_3_stati, sigla_iso_3166_1_alpha_2_stati) VALUES
(1, 'Afghanistan', '004', 'AFG', 'AF'),
(2, 'Albania', '008', 'ALB', 'AL'),
(3, 'Algeria', '012', 'DZA', 'DZ'),
(4, 'Andorra', '020', 'AND', 'AD'),
(5, 'Angola', '024', 'AGO', 'AO'),
(6, 'Anguilla', '660', 'AIA', 'AI'),
(7, 'Antartide', '010', 'ATA', 'AQ'),
(8, 'Antigua e Barbuda', '028', 'ATG', 'AG'),
(9, 'Arabia Saudita', '682', 'SAU', 'SA'),
(10, 'Argentina', '032', 'ARG', 'AR'),
(11, 'Armenia', '051', 'ARM', 'AM'),
(12, 'Aruba', '533', 'ABW', 'AW'),
(13, 'Australia', '036', 'AUS', 'AU'),
(14, 'Austria', '040', 'AUT', 'AT'),
(15, 'Azerbaigian', '031', 'AZE', 'AZ'),
(16, 'Bahamas', '044', 'BHS', 'BS'),
(17, 'Bahrein', '048', 'BHR', 'BH'),
(18, 'Bangladesh', '050', 'BGD', 'BD'),
(19, 'Barbados', '052', 'BRB', 'BB'),
(20, 'Belgio', '056', 'BEL', 'BE'),
(21, 'Belize', '084', 'BLZ', 'BZ'),
(22, 'Benin', '204', 'BEN', 'BJ'),
(23, 'Bermuda', '060', 'BMU', 'BM'),
(24, 'Bhutan', '064', 'BTN', 'BT'),
(25, 'Bielorussia', '112', 'BLR', 'BY'),
(26, 'Birmania', '104', 'MMR', 'MM'),
(27, 'Bolivia', '068', 'BOL', 'BO'),
(28, 'Bosnia ed Erzegovina', '070', 'BIH', 'BA'),
(29, 'Botswana', '072', 'BWA', 'BW'),
(30, 'Brasile', '076', 'BRA', 'BR'),
(31, 'Brunei', '096', 'BRN', 'BN'),
(32, 'Bulgaria', '100', 'BGR', 'BG'),
(33, 'Burkina Faso', '854', 'BFA', 'BF'),
(34, 'Burundi', '108', 'BDI', 'BI'),
(35, 'Cambogia', '116', 'KHM', 'KH'),
(36, 'Camerun', '120', 'CMR', 'CM'),
(37, 'Canada', '124', 'CAN', 'CA'),
(38, 'Capo Verde', '132', 'CPV', 'CV'),
(39, 'Ciad', '148', 'TCD', 'TD'),
(40, 'Cile', '152', 'CHL', 'CL'),
(41, 'Cina', '156', 'CHN', 'CN'),
(42, 'Cipro', '196', 'CYP', 'CY'),
(43, 'Citt', '336', 'VAT', 'VA'),
(44, 'Colombia', '170', 'COL', 'CO'),
(45, 'Comore', '174', 'COM', 'KM'),
(46, 'Corea del Nord', '408', 'PRK', 'KP'),
(47, 'Corea del Sud', '410', 'KOR', 'KR'),
(48, 'Costa d''Avorio', '384', 'CIV', 'CI'),
(49, 'Costa Rica', '188', 'CRI', 'CR'),
(50, 'Croazia', '191', 'HRV', 'HR'),
(51, 'Cuba', '192', 'CUB', 'CU'),
(52, 'Cura', '531', 'CUW', 'CW'),
(53, 'Danimarca', '208', 'DNK', 'DK'),
(54, 'Dominica', '212', 'DMA', 'DM'),
(55, 'Ecuador', '218', 'ECU', 'EC'),
(56, 'Egitto', '818', 'EGY', 'EG'),
(57, 'El Salvador', '222', 'SLV', 'SV'),
(58, 'Emirati Arabi Uniti', '784', 'ARE', 'AE'),
(59, 'Eritrea', '232', 'ERI', 'ER'),
(60, 'Estonia', '233', 'EST', 'EE'),
(61, 'Etiopia', '231', 'ETH', 'ET'),
(62, 'Figi', '242', 'FJI', 'FJ'),
(63, 'Filippine', '608', 'PHL', 'PH'),
(64, 'Finlandia', '246', 'FIN', 'FI'),
(65, 'Francia', '250', 'FRA', 'FR'),
(66, 'Gabon', '266', 'GAB', 'GA'),
(67, 'Gambia', '270', 'GMB', 'GM'),
(68, 'Georgia', '268', 'GEO', 'GE'),
(69, 'Georgia del Sud e isole Sandwich meridionali', '239', 'SGS', 'GS'),
(70, 'Germania', '276', 'DEU', 'DE'),
(71, 'Ghana', '288', 'GHA', 'GH'),
(72, 'Giamaica', '388', 'JAM', 'JM'),
(73, 'Giappone', '392', 'JPN', 'JP'),
(74, 'Gibilterra', '292', 'GIB', 'GI'),
(75, 'Gibuti', '262', 'DJI', 'DJ'),
(76, 'Giordania', '400', 'JOR', 'JO'),
(77, 'Grecia', '300', 'GRC', 'GR'),
(78, 'Grenada', '308', 'GRD', 'GD'),
(79, 'Groenlandia', '304', 'GRL', 'GL'),
(80, 'Guadalupa', '312', 'GLP', 'GP'),
(81, 'Guam', '316', 'GUM', 'GU'),
(82, 'Guatemala', '320', 'GTM', 'GT'),
(83, 'Guernsey', '831', 'GGY', 'GG'),
(84, 'Guinea', '324', 'GIN', 'GN'),
(85, 'Guinea-Bissau', '624', 'GNB', 'GW'),
(86, 'Guinea Equatoriale', '226', 'GNQ', 'GQ'),
(87, 'Guyana', '328', 'GUY', 'GY'),
(88, 'Guyana francese', '254', 'GUF', 'GF'),
(89, 'Haiti', '332', 'HTI', 'HT'),
(90, 'Honduras', '340', 'HND', 'HN'),
(91, 'Hong Kong', '344', 'HKG', 'HK'),
(92, 'India', '356', 'IND', 'IN'),
(93, 'Indonesia', '360', 'IDN', 'ID'),
(94, 'Iran', '364', 'IRN', 'IR'),
(95, 'Iraq', '368', 'IRQ', 'IQ'),
(96, 'Irlanda', '372', 'IRL', 'IE'),
(97, 'Islanda', '352', 'ISL', 'IS'),
(98, 'Isola Bouvet', '074', 'BVT', 'BV'),
(99, 'Isola di Man', '833', 'IMN', 'IM'),
(100, 'Isola di Natale', '162', 'CXR', 'CX'),
(101, 'Isola Norfolk', '574', 'NFK', 'NF'),
(102, 'Isole ', '248', 'ALA', 'AX'),
(103, 'Isole BES', '535', 'BES', 'BQ'),
(104, 'Isole Cayman', '136', 'CYM', 'KY'),
(105, 'Isole Cocos (Keeling)', '166', 'CCK', 'CC'),
(106, 'Isole Cook', '184', 'COK', 'CK'),
(107, 'F', '234', 'FRO', 'FO'),
(108, 'Isole Falkland', '238', 'FLK', 'FK'),
(109, 'Isole Heard e McDonald', '334', 'HMD', 'HM'),
(110, 'Isole Marianne Settentrionali', '580', 'MNP', 'MP'),
(111, 'Isole Marshall', '584', 'MHL', 'MH'),
(112, 'Isole minori esterne degli Stati Uniti', '581', 'UMI', 'UM'),
(113, 'Isole Pitcairn', '612', 'PCN', 'PN'),
(114, 'Isole Salomone', '090', 'SLB', 'SB'),
(115, 'Isole Vergini britanniche', '092', 'VGB', 'VG'),
(116, 'Isole Vergini americane', '850', 'VIR', 'VI'),
(117, 'Israele', '376', 'ISR', 'IL'),
(118, 'Italia', '380', 'ITA', 'IT'),
(119, 'Jersey', '832', 'JEY', 'JE'),
(120, 'Kazakistan', '398', 'KAZ', 'KZ'),
(121, 'Kenya', '404', 'KEN', 'KE'),
(122, 'Kirghizistan', '417', 'KGZ', 'KG'),
(123, 'Kiribati', '296', 'KIR', 'KI'),
(124, 'Kuwait', '414', 'KWT', 'KW'),
(125, 'Laos', '418', 'LAO', 'LA'),
(126, 'Lesotho', '426', 'LSO', 'LS'),
(127, 'Lettonia', '428', 'LVA', 'LV'),
(128, 'Libano', '422', 'LBN', 'LB'),
(129, 'Liberia', '430', 'LBR', 'LR'),
(130, 'Libia', '434', 'LBY', 'LY'),
(131, 'Liechtenstein', '438', 'LIE', 'LI'),
(132, 'Lituania', '440', 'LTU', 'LT'),
(133, 'Lussemburgo', '442', 'LUX', 'LU'),
(134, 'Macao', '446', 'MAC', 'MO'),
(135, 'Macedonia', '807', 'MKD', 'MK'),
(136, 'Madagascar', '450', 'MDG', 'MG'),
(137, 'Malawi', '454', 'MWI', 'MW'),
(138, 'Malesia', '458', 'MYS', 'MY'),
(139, 'Maldive', '462', 'MDV', 'MV'),
(140, 'Mali', '466', 'MLI', 'ML'),
(141, 'Malta', '470', 'MLT', 'MT'),
(142, 'Marocco', '504', 'MAR', 'MA'),
(143, 'Martinica', '474', 'MTQ', 'MQ'),
(144, 'Mauritania', '478', 'MRT', 'MR'),
(145, 'Mauritius', '480', 'MUS', 'MU'),
(146, 'Mayotte', '175', 'MYT', 'YT'),
(147, 'Messico', '484', 'MEX', 'MX'),
(148, 'Micronesia', '583', 'FSM', 'FM'),
(149, 'Moldavia', '498', 'MDA', 'MD'),
(150, 'Mongolia', '496', 'MNG', 'MN'),
(151, 'Montenegro', '499', 'MNE', 'ME'),
(152, 'Montserrat', '500', 'MSR', 'MS'),
(153, 'Mozambico', '508', 'MOZ', 'MZ'),
(154, 'Namibia', '516', 'NAM', 'NA'),
(155, 'Nauru', '520', 'NRU', 'NR'),
(156, 'Nepal', '524', 'NPL', 'NP'),
(157, 'Nicaragua', '558', 'NIC', 'NI'),
(158, 'Niger', '562', 'NER', 'NE'),
(159, 'Nigeria', '566', 'NGA', 'NG'),
(160, 'Niue', '570', 'NIU', 'NU'),
(161, 'Norvegia', '578', 'NOR', 'NO'),
(162, 'Nuova Caledonia', '540', 'NCL', 'NC'),
(163, 'Nuova Zelanda', '554', 'NZL', 'NZ'),
(164, 'Oman', '512', 'OMN', 'OM'),
(165, 'Paesi Bassi', '528', 'NLD', 'NL'),
(166, 'Pakistan', '586', 'PAK', 'PK'),
(167, 'Palau', '585', 'PLW', 'PW'),
(168, 'Palestina', '275', 'PSE', 'PS'),
(169, 'Panam', '591', 'PAN', 'PA'),
(170, 'Papua Nuova Guinea', '598', 'PNG', 'PG'),
(171, 'Paraguay', '600', 'PRY', 'PY'),
(172, 'Per', '604', 'PER', 'PE'),
(173, 'Polinesia Francese', '258', 'PYF', 'PF'),
(174, 'Polonia', '616', 'POL', 'PL'),
(175, 'Porto Rico', '630', 'PRI', 'PR'),
(176, 'Portogallo', '620', 'PRT', 'PT'),
(177, 'Monaco', '492', 'MCO', 'MC'),
(178, 'Qatar', '634', 'QAT', 'QA'),
(179, 'Regno Unito', '826', 'GBR', 'GB'),
(180, 'RD del Congo', '180', 'COD', 'CD'),
(181, 'Rep. Ceca', '203', 'CZE', 'CZ'),
(182, 'Rep. Centrafricana', '140', 'CAF', 'CF'),
(183, 'Rep. del Congo', '178', 'COG', 'CG'),
(184, 'Rep. Dominicana', '214', 'DOM', 'DO'),
(185, 'Riunione', '638', 'REU', 'RE'),
(186, 'Romania', '642', 'ROU', 'RO'),
(187, 'Ruanda', '646', 'RWA', 'RW'),
(188, 'Russia', '643', 'RUS', 'RU'),
(189, 'Sahara Occidentale', '732', 'ESH', 'EH'),
(190, 'Saint Kitts e Nevis', '659', 'KNA', 'KN'),
(191, 'Santa Lucia', '662', 'LCA', 'LC'),
(192, 'Sant''Elena, Ascensione e Tristan da Cunha', '654', 'SHN', 'SH'),
(193, 'Saint Vincent e Grenadine', '670', 'VCT', 'VC'),
(194, 'Saint-Barth', '652', 'BLM', 'BL'),
(195, 'Saint-Martin', '663', 'MAF', 'MF'),
(196, 'Saint-Pierre e Miquelon', '666', 'SPM', 'PM'),
(197, 'Samoa', '882', 'WSM', 'WS'),
(198, 'Samoa Americane', '016', 'ASM', 'AS'),
(199, 'San Marino', '674', 'SMR', 'SM'),
(200, 'S', '678', 'STP', 'ST'),
(201, 'Senegal', '686', 'SEN', 'SN'),
(202, 'Serbia', '688', 'SRB', 'RS'),
(203, 'Seychelles', '690', 'SYC', 'SC'),
(204, 'Sierra Leone', '694', 'SLE', 'SL'),
(205, 'Singapore', '702', 'SGP', 'SG'),
(206, 'Sint Maarten', '534', 'SXM', 'SX'),
(207, 'Siria', '760', 'SYR', 'SY'),
(208, 'Slovacchia', '703', 'SVK', 'SK'),
(209, 'Slovenia', '705', 'SVN', 'SI'),
(210, 'Somalia', '706', 'SOM', 'SO'),
(211, 'Spagna', '724', 'ESP', 'ES'),
(212, 'Sri Lanka', '144', 'LKA', 'LK'),
(213, 'Stati Uniti', '840', 'USA', 'US'),
(214, 'Sudafrica', '710', 'ZAF', 'ZA'),
(215, 'Sudan', '729', 'SDN', 'SD'),
(216, 'Sudan del Sud', '728', 'SSD', 'SS'),
(217, 'Suriname', '740', 'SUR', 'SR'),
(218, 'Svalbard e Jan Mayen', '744', 'SJM', 'SJ'),
(219, 'Svezia', '752', 'SWE', 'SE'),
(220, 'Svizzera', '756', 'CHE', 'CH'),
(221, 'Swaziland', '748', 'SWZ', 'SZ'),
(222, 'Taiwan', '158', 'TWN', 'TW'),
(223, 'Tagikistan', '762', 'TJK', 'TJ'),
(224, 'Tanzania', '834', 'TZA', 'TZ'),
(225, 'Terre australi e antartiche francesi', '260', 'ATF', 'TF'),
(226, 'Territorio britannico dell''oceano Indiano', '086', 'IOT', 'IO'),
(227, 'Thailandia', '764', 'THA', 'TH'),
(228, 'Timor Est', '626', 'TLS', 'TL'),
(229, 'Togo', '768', 'TGO', 'TG'),
(230, 'Tokelau', '772', 'TKL', 'TK'),
(231, 'Tonga', '776', 'TON', 'TO'),
(232, 'Trinidad e Tobago', '780', 'TTO', 'TT'),
(233, 'Tunisia', '788', 'TUN', 'TN'),
(234, 'Turchia', '792', 'TUR', 'TR'),
(235, 'Turkmenistan', '795', 'TKM', 'TM'),
(236, 'Turks e Caicos', '796', 'TCA', 'TC'),
(237, 'Tuvalu', '798', 'TUV', 'TV'),
(238, 'Ucraina', '804', 'UKR', 'UA'),
(239, 'Uganda', '800', 'UGA', 'UG'),
(240, 'Ungheria', '348', 'HUN', 'HU'),
(241, 'Uruguay', '858', 'URY', 'UY'),
(242, 'Uzbekistan', '860', 'UZB', 'UZ'),
(243, 'Vanuatu', '548', 'VUT', 'VU'),
(244, 'Venezuela', '862', 'VEN', 'VE'),
(245, 'Vietnam', '704', 'VNM', 'VN'),
(246, 'Wallis e Futuna', '876', 'WLF', 'WF'),
(247, 'Yemen', '887', 'YEM', 'YE'),
(248, 'Zambia', '894', 'ZMB', 'ZM'),
(249, 'Zimbabwe', '716', 'ZWE', 'ZW');

--SIMFITOLAB - modifica metodi
ALTER TABLE simfitolab.agent ADD COLUMN enabled BOOLEAN DEFAULT false;
UPDATE simfitolab.agent set enabled=true WHERE agent.id in (
  select agent.id
  from simfitolab.analisyssection 
  inner join simfitolab.method on method.analisyssection_id=analisyssection.id 
  inner join simfitolab.agent on agent.method_id=method.id
  where method.laboratorio_id=0
);
ALTER TABLE simfitolab.method ADD COLUMN enabled BOOLEAN DEFAULT false;
UPDATE simfitolab.method SET enabled=true WHERE laboratorio_id=0;

/*
  select agent.id, agent.name, analisyssection.name
  from simfitolab.analisyssection 
  inner join simfitolab.method on method.analisyssection_id=analisyssection.id 
  inner join simfitolab.agent on agent.method_id=method.id
  where agent.enabled  and method.enabled and analisyssection.name='Batteriologia' --and method.laboratorio_id=0
  order by agent.id;
  select * from simfito.tipologiasito where theme ilike 'Produzione, commmercio e trasporti di materiale vegetale%'
  update in 'Produzione, commmercio e trasporti di materiale vegetale regolamentato' tipo update simfito.tipologiasito set theme='Produzione, commmercio e trasporti di materiale vegetale regolamentato' where theme_id=6
*/

--disabilitazione siti non usati da più di 4 anno (prima del 2016)
with a as (
	select max(data_sopralluogo) as data, gid_sito 
	from simfito.scheda
	inner join simfito.siti on scheda.gid_sito=siti.gid
	group by gid_sito
	having max(data_sopralluogo) < '2016-01-01'
	order by data
)
/*select count(*), cancellato 
from simfito.siti 
where gid in (select gid_sito from a)
group by cancellato*/
update simfito.siti set cancellato=true where gid in (select gid_sito from a)
--select count (*), cancellato from simfito.siti group by cancellato

--add sequence to id tipo_trappole
CREATE SEQUENCE simfito.tipo_trappole_id_seq
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 2147483648 START 1
        CACHE 1;
ALTER TABLE simfito.tipo_trappole ALTER COLUMN id
        SET DEFAULT nextval('simfito.tipo_trappole_id_seq'::regclass);
--check max id
/*with a as(
	select max(id)+1 as max_id from simfito.tipo_trappole
)
--select max_id from a*/
-- restart sequence
ALTER SEQUENCE simfito.tipo_trappole_id_seq RESTART with 18;

--Pest rendicontati
CREATE TABLE simfito.rendicontati
(
  id serial NOT NULL,
  host character varying NOT NULL,
  pest character varying NOT NULL,
  enabled boolean DEFAULT true,
  date date DEFAULT now(),
  CONSTRAINT rendicontati_pkey PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE simfito.rendicontati
  OWNER TO postgres;

INSERT INTO simfito.rendicontati (host,pest) values
('BETAS','AGRLAX'),
('BETAL','AGRLAX'),
('BETDA','AGRLAX'),
('BETER','AGRLAX'),
('BETLE','AGRLAX'),
('BETMA','AGRLAX'),
('BETOC','AGRLAX'),
('BETPA','AGRLAX'),
('BETPE','AGRLAX'),
('BETPL','AGRLAX'),
('BETPJ','AGRLAX'),
('BETPS','AGRLAX'),
('BETPO','AGRLAX'),
('BETPB','AGRLAX'),
('BETJQ','AGRLAX'),
('1BETG','AGRLAX'),
('BETNI','AGRLAX'),
('BETPM','AGRLAX'),
('FRXAM','AGRLPL'),
('FRXAX','AGRLPL'),
('FRXCH','AGRLPL'),
('FRXEX','AGRLPL'),
('FRXJA','AGRLPL'),
('FRXLN','AGRLPL'),
('FRXNI','AGRLPL'),
('FRXOR','AGRLPL'),
('FRXPE','AGRLPL'),
('FRXQU','AGRLPL'),
('FRXRH','AGRLPL'),
('FRXUH','AGRLPL'),
('FRXVE','AGRLPL'),
('1FRXG','AGRLPL'),
('FRXMA','AGRLPL'),
('CIOVI','AGRLPL'),
('IUGAI','AGRLPL'),
('IUGMN','AGRLPL'),
('PTFRH','AGRLPL'),
('ULMDA','AGRLPL'),
('OLVEU','AGRLPL'),
('CIDLI','ALECSN'),
('CIDME','ALECSN'),
('CIDRE','ALECSN'),
('CIDSI','ALECSN'),
('DOSKA','ALECSN'),
('1FOLG','ALECSN'),
('PYUCO','ALECSN'),
('1ROSG','ALECSN'),
('VITVI','ALECSN'),
('AILAL','ALECSN'),
('AKELO','ALECSN'),
('AKETF','ALECSN'),
('ALUFO','ALECSN'),
('ANUMU','ALECSN'),
('ANURE','ALECSN'),
('ANUSQ','ALECSN'),
('ANUAT','ALECSN'),
('APTPH','ALECSN'),
('ARDUN','ALECSN'),
('BGTAC','ALECSN'),
('BAUCH','ALECSN'),
('BOHVD','ALECSN'),
('BOHZB','ALECSN'),
('CWSAC','ALECSN'),
('CEQSI','ALECSN'),
('CINCA','ALECSN'),
('CIDAU','ALECSN'),
('CLVVT','ALECSN'),
('CCNNU','ALECSN'),
('CJQAN','ALECSN'),
('CYDSS','ALECSN'),
('DOSMR','ALECSN'),
('ENTPH','ALECSN'),
('EIOJA','ALECSN'),
('EYBHE','ALECSN'),
('FATSS','ALECSN'),
('FIUCA','ALECSN'),
('FIURM','ALECSN'),
('FIUSS','ALECSN'),
('FIUSU','ALECSN'),
('FLISS','ALECSN'),
('GNHFA','ALECSN'),
('GADJA','ALECSN'),
('GOSSS','ALECSN'),
('HEEHE','ALECSN'),
('HIBCA','ALECSN'),
('HIBRS','ALECSN'),
('HIBTI','ALECSN'),
('LURNO','ALECSN'),
('LIQFO','ALECSN'),
('MCRTA','ALECSN'),
('MCHZU','ALECSN'),
('MBEPE','ALECSN'),
('MABSS','ALECSN'),
('MALSS','ALECSN'),
('MANES','ALECSN'),
('MRSCO','ALECSN'),
('MLORI','ALECSN'),
('MYRRU','ALECSN'),
('MORAL','ALECSN'),
('MUYKO','ALECSN'),
('MDAPU','ALECSN'),
('PRTTR','ALECSN'),
('PEBAM','ALECSN'),
('PBOFO','ALECSN'),
('PIPKA','ALECSN'),
('PIAVE','ALECSN'),
('PLIRU','ALECSN'),
('PRNAR','ALECSN'),
('PRNAV','ALECSN'),
('PRNCE','ALECSN'),
('PRNDO','ALECSN'),
('PRNPS','ALECSN'),
('PRNSO','ALECSN'),
('PSIGU','ALECSN'),
('PUNGR','ALECSN'),
('PYECO','ALECSN'),
('PYUPS','ALECSN'),
('PYUPY','ALECSN'),
('RHOLH','ALECSN'),
('RLLMU','ALECSN'),
('ROSBA','ALECSN'),
('ROSCH','ALECSN'),
('ROSID','ALECSN'),
('ROSDM','ALECSN'),
('SAXSS','ALECSN'),
('SKOOL','ALECSN'),
('CASSM','ALECSN'),
('SLEDA','ALECSN'),
('SBWSS','ALECSN'),
('SYDNO','ALECSN'),
('SYZSA','ALECSN'),
('TOOCI','ALECSN'),
('SAQSE','ALECSN'),
('URNLO','ALECSN'),
('VIGSQ','ALECSN'),
('XYOCO','ALECSN'),
('ZANNI','ALECSN'),
('PRNDO','APLPV0'),
('1PRNG','APLPV0'),
('PRNPS','APLPV0'),
('PRNSL','APLPV0'),
('PRNAR','APLPV0'),
('NIOME','APLPV0'),
('VIGSC','APLPV0'),
('CIDAF','ANSTLU'),
('CIDAU','ANSTLU'),
('CIDPA','ANSTLU'),
('CIDRE','ANSTLU'),
('CIDSI','ANSTLU'),
('MNGIN','ANSTLU'),
('ANURE','ANSTLU'),
('CPSPU','ANSTLU'),
('CSJED','ANSTLU'),
('1CIDG','ANSTLU'),
('CIDDE','ANSTLU'),
('CIDLM','ANSTLU'),
('CIDGR','ANSTLU'),
('CIDME','ANSTLU'),
('CIDMY','ANSTLU'),
('CIDRH','ANSTLU'),
('CIDRP','ANSTLU'),
('MAFAM','ANSTLU'),
('PRNPS','ANSTLU'),
('PSICA','ANSTLU'),
('PSIGU','ANSTLU'),
('PSIGN','ANSTLU'),
('PSIOL','ANSTLU'),
('PUNGR','ANSTLU'),
('PYUCO','ANSTLU'),
('SPXPU','ANSTLU'),
('SYZJA','ANSTLU'),
('ANAOC','ANSTLU'),
('ANUCH','ANSTLU'),
('ANUSQ','ANSTLU'),
('COFAR','ANSTLU'),
('CYDOB','ANSTLU'),
('DOSKA','ANSTLU'),
('INGJI','ANSTLU'),
('MABSD','ANSTLU'),
('MLCOL','ANSTLU'),
('PAQED','ANSTLU'),
('PEBAM','ANSTLU'),
('ANULI','ANSTLU'),
('SGTGR','ANSTLU'),
('CSJPU','ANSTLU'),
('CSJTE','ANSTLU'),
('DOSTE','ANSTLU'),
('INGFL','ANSTLU'),
('SDICT','ANSTLU'),
('FEJSE','ANSTLU'),
('CPSAN','ANSTLU'),
('CIAPA','ANSTLU'),
('CISMA','ANSTLU'),
('CUUSS','ANSTLU'),
('EIOJA','ANSTLU'),
('FIUSS','ANSTLU'),
('HCRSS','ANSTLU'),
('IUGRE','ANSTLU'),
('MNKZA','ANSTLU'),
('MUBSS','ANSTLU'),
('OPUSS','ANSTLU'),
('PHYSS','ANSTLU'),
('SDIPA','ANSTLU'),
('CYJBE','ANSTLU'),
('LYPES','ANSTLU'),
('SPXMO','ANSTLU'),
('SVCSS','ANSTLU'),
('CYLAV','CRSPAN'),
('1CYLG','CRSPAN'),
('CYLMA','CRSPAN'),
('1ACRG','ANOLCN'),
('ACRPA','ANOLCN'),
('ACRSA','ANOLCN'),
('AECHI','ANOLCN'),
('1ALUG','ANOLCN'),
('1BETG','ANOLCN'),
('1CIPG','ANOLCN'),
('1CIDG','ANOLCN'),
('CIDLI','ANOLCN'),
('CIDRE','ANOLCN'),
('CIDSI','ANOLCN'),
('CYLAV','ANOLCN'),
('1CTTG','ANOLCN'),
('1FAUG','ANOLCN'),
('1LAEG','ANOLCN'),
('LAEIN','ANOLCN'),
('1MABG','ANOLCN'),
('1PLTG','ANOLCN'),
('PLTOC','ANOLCN'),
('PLTOR','ANOLCN'),
('1POPG','ANOLCN'),
('1PRNG','ANOLCN'),
('1PYUG','ANOLCN'),
('1ULMG','ANOLCN'),
('1CSNG','ANOLCN'),
('1CRWG','ANOLCN'),
('1CSCG','ANOLCN'),
('CMYJA','ANOLCN'),
('1FIUG','ANOLCN'),
('1HIBG','ANOLCN'),
('1IUGG','ANOLCN'),
('LIHCH','ANOLCN'),
('MEIAZ','ANOLCN'),
('1MORG','ANOLCN'),
('1ROSG','ANOLCN'),
('1SAXG','ANOLCN'),
('1VACG','ANOLCN'),
('1ACAG','ANOLCN'),
('ACADC','ANOLCN'),
('ACRCA','ANOLCN'),
('ACRNE','ANOLCN'),
('ACROB','ANOLCN'),
('ACRMO','ANOLCN'),
('ACRPL','ANOLCN'),
('ACRPP','ANOLCN'),
('1AECG','ANOLCN'),
('1ALBG','ANOLCN'),
('ALBJU','ANOLCN'),
('CSUST','ANOLCN'),
('ALUFI','ANOLCN'),
('ALUFM','ANOLCN'),
('ALUHI','ANOLCN'),
('ALUMX','ANOLCN'),
('ALUSB','ANOLCN'),
('1ARLG','ANOLCN'),
('ARLCO','ANOLCN'),
('SEVBU','ANOLCN'),
('BETPE','ANOLCN'),
('BETPL','ANOLCN'),
('BETPJ','ANOLCN'),
('BRNPA','ANOLCN'),
('RHUJV','ANOLCN'),
('1CAJG','ANOLCN'),
('CAJCA','ANOLCN'),
('1CAHG','ANOLCN'),
('CAHOL','ANOLCN'),
('CIPBE','ANOLCN'),
('CIPLA','ANOLCN'),
('CYAIL','ANOLCN'),
('CSNCR','ANOLCN'),
('1CSOG','ANOLCN'),
('CSOCS','ANOLCN'),
('1CSUG','ANOLCN'),
('CSUEQ','ANOLCN'),
('1CTLG','ANOLCN'),
('1CCSG','ANOLCN'),
('1CNMG','ANOLCN'),
('CIDAF','ANOLCN'),
('CIDAU','ANOLCN'),
('CIDJU','ANOLCN'),
('CIDGR','ANOLCN'),
('CIDUN','ANOLCN'),
('CIDLO','ANOLCN'),
('CIDNO','ANOLCN'),
('1ELGG','ANOLCN'),
('ELGMU','ANOLCN'),
('ELGUM','ANOLCN'),
('1EIOG','ANOLCN'),
('EIOJA','ANOLCN'),
('FAUCR','ANOLCN'),
('FAUSY','ANOLCN'),
('FIUCA','ANOLCN'),
('1FOLG','ANOLCN'),
('FOLMA','ANOLCN'),
('1FRXG','ANOLCN'),
('FRXAM','ANOLCN'),
('1GREG','ANOLCN'),
('1HEEG','ANOLCN'),
('HEERH','ANOLCN'),
('HIBMU','ANOLCN'),
('HIBSY','ANOLCN'),
('1ILEG','ANOLCN'),
('ILECH','ANOLCN'),
('IUGMN','ANOLCN'),
('1LIEG','ANOLCN'),
('LIEPR','ANOLCN'),
('1LIQG','ANOLCN'),
('1LIHG','ANOLCN'),
('1MCKG','ANOLCN'),
('MCKAM','ANOLCN'),
('PEBTH','ANOLCN'),
('1MLLG','ANOLCN'),
('MLLJA','ANOLCN'),
('MABAC','ANOLCN'),
('MABSD','ANOLCN'),
('MABSY','ANOLCN'),
('1MEIG','ANOLCN'),
('MOMCH','ANOLCN'),
('MORAL','ANOLCN'),
('MORBO','ANOLCN'),
('1OLVG','ANOLCN'),
('OLVEU','ANOLCN'),
('1OSTG','ANOLCN'),
('1PEBG','ANOLCN'),
('PLTHY','ANOLCN'),
('1PMIG','ANOLCN'),
('PMITR','ANOLCN'),
('POPAL','ANOLCN'),
('POPMA','ANOLCN'),
('POPNI','ANOLCN'),
('POPSI','ANOLCN'),
('POPTO','ANOLCN'),
('PRNAR','ANOLCN'),
('PRNLR','ANOLCN'),
('PRNYE','ANOLCN'),
('1PSIG','ANOLCN'),
('PSIGU','ANOLCN'),
('PUNGR','ANOLCN'),
('1PYEG','ANOLCN'),
('PYEAN','ANOLCN'),
('PYUPY','ANOLCN'),
('PYUPC','ANOLCN'),
('PYUUS','ANOLCN'),
('1QUEG','ANOLCN'),
('QUEAS','ANOLCN'),
('QUEGU','ANOLCN'),
('QUEPE','ANOLCN'),
('QUERO','ANOLCN'),
('QUEGL','ANOLCN'),
('1RHOG','ANOLCN'),
('1RHUG','ANOLCN'),
('1ROBG','ANOLCN'),
('ROBPS','ANOLCN'),
('ROSMU','ANOLCN'),
('ROSRG','ANOLCN'),
('1RUBG','ANOLCN'),
('RUBMI','ANOLCN'),
('RUBPM','ANOLCN'),
('1SGRG','ANOLCN'),
('SAXBA','ANOLCN'),
('SAXGS','ANOLCN'),
('SAXIG','ANOLCN'),
('SAXKO','ANOLCN'),
('SAXJE','ANOLCN'),
('1SAMG','ANOLCN'),
('1SAQG','ANOLCN'),
('1SOBG','ANOLCN'),
('1SOUG','ANOLCN'),
('1STVG','ANOLCN'),
('STXJA','ANOLCN'),
('1TOOG','ANOLCN'),
('TOXVE','ANOLCN'),
('SAQSE','ANOLCN'),
('ULMJA','ANOLCN'),
('1VNIG','ANOLCN'),
('ALEFO','ANOLCN'),
('1VIBG','ANOLCN'),
('ZANSI','ANOLCN'),
('1ZELG','ANOLCN'),
('1ZIPG','ANOLCN'),
('ACRBU','ANOLGL'),
('ACRNE','ANOLGL'),
('ACRPE','ANOLGL'),
('ACRMO','ANOLGL'),
('ACRPL','ANOLGL'),
('ACRPP','ANOLGL'),
('ACRRB','ANOLGL'),
('ACRSA','ANOLGL'),
('ACRSC','ANOLGL'),
('ACRTU','ANOLGL'),
('AECHI','ANOLGL'),
('BETNI','ANOLGL'),
('1POPG','ANOLGL'),
('POPDE','ANOLGL'),
('POPNI','ANOLGL'),
('POPCA','ANOLGL'),
('1SAXG','ANOLGL'),
('SAXBA','ANOLGL'),
('ACRTG','ANOLGL'),
('ALBJU','ANOLGL'),
('CYLCO','ANOLGL'),
('ELGAN','ANOLGL'),
('1FAUG','ANOLGL'),
('FAUSY','ANOLGL'),
('1FRXG','ANOLGL'),
('FRXPE','ANOLGL'),
('KOTPA','ANOLGL'),
('MABSD','ANOLGL'),
('MORAL','ANOLGL'),
('1PLTG','ANOLGL'),
('PRNSL','ANOLGL'),
('PYUBR','ANOLGL'),
('1ACRG','ANOLGL'),
('ACRPS','ANOLGL'),
('1ALBG','ANOLGL'),
('1ALUG','ANOLGL'),
('1BETG','ANOLGL'),
('BETPE','ANOLGL'),
('BRNPA','ANOLGL'),
('CAJCA','ANOLGL'),
('1CIPG','ANOLGL'),
('CIPBE','ANOLGL'),
('1CSUG','ANOLGL'),
('1CETG','ANOLGL'),
('1CCPG','ANOLGL'),
('1GLIG','ANOLGL'),
('1KOTG','ANOLGL'),
('MLLJA','ANOLGL'),
('1MABG','ANOLGL'),
('1MEIG','ANOLGL'),
('MEIAZ','ANOLGL'),
('1MORUG','ANOLGL'),
('PLTOR','ANOLGL'),
('POPCT','ANOLGL'),
('POPLA','ANOLGL'),
('POPMA','ANOLGL'),
('POPSM','ANOLGL'),
('QUERU','ANOLGL'),
('SAXNI','ANOLGL'),
('1SOUG','ANOLGL'),
('1ULMG','ANOLGL'),
('ULMAM','ANOLGL'),
('ULMPA','ANOLGL'),
('ULMPU','ANOLGL'),
('ALEMN','ANOLGL'),
('POPBA','ANOLGL'),
('SOUAU','ANOLGL'),
('CPSAN','ANTHEU'),
('CPSFR','ANTHEU'),
('CPSBA','ANTHEU'),
('NIOAL','ANTHEU'),
('PHYIX','ANTHEU'),
('SOLAV','ANTHEU'),
('SOLMX','ANTHEU'),
('SOLME','ANTHEU'),
('SOLPC','ANTHEU'),
('1CPSG','ANTHEU'),
('1SOLG','ANTHEU'),
('DATST','ANTHEU'),
('SOLAM','ANTHEU'),
('SOLCA','ANTHEU'),
('SOLEL','ANTHEU'),
('SOLNI','ANTHEU'),
('SOLRS','ANTHEU'),
('SOLXN','ANTHEU'),
('SOLLU','ANTHEU'),
('PRNAM','AROMBU'),
('PRNAR','AROMBU'),
('PRNAV','AROMBU'),
('PRNCF','AROMBU'),
('PRNDO','AROMBU'),
('PRNDT','AROMBU'),
('PRNGN','AROMBU'),
('PRNJP','AROMBU'),
('PRNMM','AROMBU'),
('PRNPS','AROMBU'),
('PRNPC','AROMBU'),
('PRNSC','AROMBU'),
('PRNSO','AROMBU'),
('PRNYE','AROMBU'),
('CSNMO','AROMBU'),
('IUGRE','AROMBU'),
('LYPES','PARZCO'),
('SOLTU','PARZCO'),
('CPSAN','PARZCO'),
('IPOBA','PARZCO'),
('1LYUG','PARZCO'),
('1MENG','PARZCO'),
('MMJCH','PARZCO'),
('1NEPG','PARZCO'),
('NIOTA','PARZCO'),
('SOLME','PARZCO'),
('CONAR','PARZCO'),
('NICPH','PARZCO'),
('SOLDU','PARZCO'),
('ANAOC','DACUDO'),
('ANUMU','DACUDO'),
('CIAPA','DACUDO'),
('THVPE','DACUDO'),
('CIDPA','DACUDO'),
('CIDRE','DACUDO'),
('CIDSI','DACUDO'),
('CIDRP','DACUDO'),
('DMCLO','DACUDO'),
('DOSMN','DACUDO'),
('EIOJA','DACUDO'),
('FOLJA','DACUDO'),
('CSFAL','DACUDO'),
('IRVGA','DACUDO'),
('MNGIN','DACUDO'),
('MUBPA','DACUDO'),
('PRNPS','DACUDO'),
('PSICA','DACUDO'),
('PSIGU','DACUDO'),
('SPXDU','DACUDO'),
('SPXMO','DACUDO'),
('TEMCA','DACUDO'),
('VILPA','DACUDO'),
('1ANUG','DACUDO'),
('ANUCH','DACUDO'),
('ANUSE','DACUDO'),
('ANUSQ','DACUDO'),
('AVRCA','DACUDO'),
('1CPSG','DACUDO'),
('CPSAN','DACUDO'),
('CPSFR','DACUDO'),
('CITLA','DACUDO'),
('1CIDG','DACUDO'),
('CIDAF','DACUDO'),
('CIDAU','DACUDO'),
('CIDLI','DACUDO'),
('CIDGR','DACUDO'),
('CUSLA','DACUDO'),
('COFAR','DACUDO'),
('COFCA','DACUDO'),
('CRHMY','DACUDO'),
('CUMSA','DACUDO'),
('CUUMA','DACUDO'),
('CUUPE','DACUDO'),
('CYDOB','DACUDO'),
('1DOSG','DACUDO'),
('FLCIN','DACUDO'),
('1FOLG','DACUDO'),
('2FRUT','DACUDO'),
('LGNSI','DACUDO'),
('1MABG','DACUDO'),
('MABSD','DACUDO'),
('MNKZA','DACUDO'),
('MOMCH','DACUDO'),
('1MUBG','DACUDO'),
('PEBAM','DACUDO'),
('PRNDO','DACUDO'),
('PRNSC','DACUDO'),
('1PYUG','DACUDO'),
('PYUCO','DACUDO'),
('SLCBB','DACUDO'),
('SOLAE','DACUDO'),
('SOLAG','DACUDO'),
('SOLIA','DACUDO'),
('SOLSO','DACUDO'),
('LYPES','DACUDO'),
('SOLME','DACUDO'),
('1SPXG','DACUDO'),
('SYZCU','DACUDO'),
('SYZJA','DACUDO'),
('SYZMA','DACUDO'),
('SYZSA','DACUDO'),
('THOCA','DACUDO'),
('VITVI','DACUDO'),
('ZIPMA','DACUDO'),
('1COFG','DACUDO'),
('PRNAR','DACUDO'),
('PRNDU','DACUDO'),
('PIPNI','DACUDO'),
('SOLNI','DACUDO'),
('1SYHG','DACUDO'),
('MNGIN','DACUZO'),
('PRNPS','DACUZO'),
('PSIGU','DACUZO'),
('ABMES','DACUZO'),
('AELMA','DACUZO'),
('AFZCO','DACUZO'),
('ANURE','DACUZO'),
('ANUSQ','DACUZO'),
('CBRAR','DACUZO'),
('CIAPA','DACUZO'),
('CITLA','DACUZO'),
('CIDAU','DACUZO'),
('CIDLI','DACUZO'),
('CIDPA','DACUZO'),
('CIDRE','DACUZO'),
('CIDSI','DACUZO'),
('COCGR','DACUZO'),
('CUMSA','DACUZO'),
('CUUSS','DACUZO'),
('CYDOB','DACUZO'),
('DOSSS','DACUZO'),
('EAEHY','DACUZO'),
('EIOJA','DACUZO'),
('FIUCA','DACUZO'),
('GRWAS','DACUZO'),
('LGNSI','DACUZO'),
('LUFAC','DACUZO'),
('MLPEM','DACUZO'),
('MABSD','DACUZO'),
('MNKZA','DACUZO'),
('MMOEL','DACUZO'),
('MOMCH','DACUZO'),
('PEBAM','DACUZO'),
('PHXDA','DACUZO'),
('PRNAR','DACUZO'),
('PSICA','DACUZO'),
('PUNGR','DACUZO'),
('DRPRO','DACUZO'),
('PYUCO','DACUZO'),
('PYUUS','DACUZO'),
('SYZJA','DACUZO'),
('SYZSA','DACUZO'),
('TEMCA','DACUZO'),
('ZIPJU','DACUZO'),
('ZIPMA','DACUZO'),
('VACCO','BLMOV0'),
('1VACG','BLMOV0'),
('VACAN','BLMOV0'),
('VACML','BLMOV0'),
('1VITG','BLMOV0'),
('VITVI','BLMOV0'),
('VITLA','BLMOV0'),
('PIUDE','BURSXY'),
('PIUSI','BURSXY'),
('1ABIG','BURSXY'),
('1CEUG','BURSXY'),
('1LAXG','BURSXY'),
('1PIUG','BURSXY'),
('PIUAR','BURSXY'),
('PIUBU','BURSXY'),
('PIUEC','BURSXY'),
('PIUEL','BURSXY'),
('PIUKO','BURSXY'),
('PIULA','BURSXY'),
('PIULU','BURSXY'),
('PIUMA','BURSXY'),
('PIUNI','BURSXY'),
('PIUPL','BURSXY'),
('PIUPI','BURSXY'),
('PIURA','BURSXY'),
('PIUTA','BURSXY'),
('PIUTD','BURSXY'),
('PIUTH','BURSXY'),
('1PSTG','BURSXY'),
('1TSUG','BURSXY'),
('ABIBA','BURSXY'),
('CEUAT','BURSXY'),
('CEUDE','BURSXY'),
('LAXDE','BURSXY'),
('LAXLA','BURSXY'),
('PIEAB','BURSXY'),
('PIEPU','BURSXY'),
('PSTME','BURSXY'),
('TSUCA','BURSXY'),
('CIDRE','LIBEAF'),
('CIDSI','LIBEAF'),
('CIDRP','LIBEAF'),
('1CJCG','LIBEAF'),
('1CIDG','LIBEAF'),
('CIDJA','LIBEAF'),
('CIDLT','LIBEAF'),
('CIDLI','LIBEAF'),
('CIDME','LIBEAF'),
('CIDPA','LIBEAF'),
('CIDLO','LIBEAF'),
('1FOLG','LIBEAF'),
('PMITR','LIBEAF'),
('CJFMI','LIBEAF'),
('CIDAF','LIBEAF'),
('CIDGR','LIBEAF'),
('1RUTF','LIBEAF'),
('CTURO','LIBEAF'),
('CIDSI','LIBEAM'),
('CIDRE','LIBEAS'),
('CIDSI','LIBEAS'),
('CIDRP','LIBEAS'),
('SEVBU','LIBEAS'),
('1CJCG','LIBEAS'),
('1CIDG','LIBEAS'),
('CIDAF','LIBEAS'),
('CIDJA','LIBEAS'),
('CIDLT','LIBEAS'),
('CIDLI','LIBEAS'),
('CIDGR','LIBEAS'),
('CIDME','LIBEAS'),
('CIDPA','LIBEAS'),
('CIDLO','LIBEAS'),
('CUSLA','LIBEAS'),
('1FOLG','LIBEAS'),
('FOLMA','LIBEAS'),
('MUYPA','LIBEAS'),
('PMITR','LIBEAS'),
('SWNGL','LIBEAS'),
('CJFMI','LIBEAS'),
('1AYAG','LIBEAS'),
('CIDMS','LIBEAS'),
('CIDMP','LIBEAS'),
('FEOLI','LIBEAS'),
('1RUTF','LIBEAS'),
('1TDDG','LIBEAS'),
('CLERT','LIBEAS'),
('PISAC','LIBEAS'),
('TSGOC','LIBEAS'),
('CTURO','LIBEAS'),
('VITVI','CARNFU'),
('CYNDA','CARNFU'),
('ECHCG','CARNFU'),
('1GRAF','CARNFU'),
('PLTOR','CERAFP'),
('PLTHY','CERAFP'),
('PLTOC','CERAFP'),
('PLTRA','CERAFP'),
('PRNAV','CRLV00'),
('PRNPS','CRLV00'),
('MABSD','CRLV00'),
('PRNMH','CRLV00'),
('SAMNI','CRLV00'),
('CMOTE','CRLV00'),
('ATXHO','CRLV00'),
('BLZSA','CRLV00'),
('CHEMU','CRLV00'),
('CUUMA','CRLV00'),
('GOMGL','CRLV00'),
('NIOSS','CRLV00'),
('OCIBA','CRLV00'),
('PHSVX','CRLV00'),
('PHYFL','CRLV00'),
('RUBID','CRLV00'),
('SEBEX','CRLV00'),
('CYJBE','CRLV00'),
('LYPES','CRLV00'),
('SOLSI','CRLV00'),
('SOLTU','CRLV00'),
('MALSS','CRLV00'),
('PLAMA','CRLV00'),
('TAROF','CRLV00'),
('CHEAL','CRLV00'),
('CHEGI','CRLV00'),
('CHEQU','CRLV00'),
('CUMSA','CRLV00'),
('CHYHO','CSNV00'),
('LYPES','CSNV00'),
('EVMGR','CSNV00'),
('GEBSS','CSNV00'),
('CIDAU','CTV000'),
('CIDSI','CTV000'),
('1CJCG','CTV000'),
('1CIDG','CTV000'),
('CIDAF','CTV000'),
('CIDLT','CTV000'),
('CIDPA','CTV000'),
('CJFMI','CTV000'),
('AEZCH','CTV000'),
('AFQPA','CTV000'),
('ABAXA','CTV000'),
('CJCWE','CTV000'),
('CIQGI','CTV000'),
('1CUSG','CTV000'),
('1FOLG','CTV000'),
('PBBMI','CTV000'),
('PMITR','CTV000'),
('1PAQG','CTV000'),
('SOLTU','CORBSE'),
('BEAVX','CORBSE'),
('LYPES','CORBSE'),
('SOLME','CORBSE'),
('HEGLI','CONHNE'),
('PRNDO','CONHNE'),
('PRNPS','CONHNE'),
('AMEAR','CONHNE'),
('AMECA','CONHNE'),
('1CSCG','CONHNE'),
('CYDOB','CONHNE'),
('1HEGG','CONHNE'),
('1MABG','CONHNE'),
('MABSD','CONHNE'),
('1PRNG','CONHNE'),
('PRNAR','CONHNE'),
('PRNAV','CONHNE'),
('PRNCE','CONHNE'),
('PRNSC','CONHNE'),
('PRNSO','CONHNE'),
('1PYUG','CONHNE'),
('PYUCO','CONHNE'),
('1VACG','CONHNE'),
('VACCO','CONHNE'),
('VACST','CONHNE'),
('VITRF','CONHNE'),
('PRNMM','CONHNE'),
('1RIBG','CONHNE'),
('CSCAE','CONHNE'),
('PRNAL','CONHNE'),
('PRNAM','CONHNE'),
('PRNAN','CONHNE'),
('PRNMR','CONHNE'),
('PRNME','CONHNE'),
('PRNNI','CONHNE'),
('PRNPE','CONHNE'),
('PRNPU','CONHNE'),
('PRNUM','CONHNE'),
('PRNVG','CONHNE'),
('SOUAU','CONHNE'),
('1ABIG','DACLPI'),
('PIUCO','DACLPI'),
('PIUDE','DACLPI'),
('PIUHA','DACLPI'),
('PIUKO','DACLPI'),
('PIUMA','DACLPI'),
('PIUNI','DACLPI'),
('PIUPF','DACLPI'),
('PIUPL','DACLPI'),
('PIUPN','DACLPI'),
('PIURA','DACLPI'),
('PIUTA','DACLPI'),
('PIUTH','DACLPI'),
('ABINE','DENDSI'),
('ABISB','DENDSI'),
('LAXGM','DENDSI'),
('LAXSI','DENDSI'),
('PIEJE','DENDSI'),
('PIEOB','DENDSI'),
('PIUKO','DENDSI'),
('PIUSB','DENDSI'),
('1ABIG','DENDSI'),
('1LAXG','DENDSI'),
('1PIEG','DENDSI'),
('1PIUG','DENDSI'),
('PSTME','DENDSI'),
('1TSUG','DENDSI'),
('VITVI','DRAEMI'),
('CYNDA','DRAEMI'),
('ECHCG','DRAEMI'),
('1GRAF','DRAEMI'),
('CIDRE','ELSIAU'),
('CIDSI','ELSIAU'),
('CIDAF','ELSIAU'),
('CIDAU','ELSIAU'),
('CIDDE','ELSIAU'),
('CIDJA','ELSIAU'),
('CIDLI','ELSIAU'),
('CIDNA','ELSIAU'),
('CIDPA','ELSIAU'),
('CIDUN','ELSIAU'),
('CIDNO','ELSIAU'),
('FOLMA','ELSIAU'),
('PMITR','ELSIAU'),
('POPDE','ELSIAU'),
('POPTO','ELSIAU'),
('SMMCH','ELSIAU'),
('CJFMI','ELSIAU'),
('CIDAC','ELSIAU'),
('CIDHY','ELSIAU'),
('1CIDG','ELSICI'),
('CIDAU','ELSIFA'),
('CIDLI','ELSIFA'),
('CIDPA','ELSIFA'),
('CIDRE','ELSIFA'),
('CIDRP','ELSIFA'),
('1CJCG','ELSIFA'),
('1CIDG','ELSIFA'),
('CIDDE','ELSIFA'),
('CIDHY','ELSIFA'),
('CIDJA','ELSIFA'),
('CIDLA','ELSIFA'),
('CIDGR','ELSIFA'),
('CIDME','ELSIFA'),
('CIDSI','ELSIFA'),
('CIDUN','ELSIFA'),
('CIDLO','ELSIFA'),
('CIDNO','ELSIFA'),
('1FOLG','ELSIFA'),
('FOLJA','ELSIFA'),
('FOLMA','ELSIFA'),
('PMITR','ELSIFA'),
('CJFMI','ELSIFA'),
('CIDAF','ELSIFA'),
('CIDLI','EOTELE'),
('CIDPA','EOTELE'),
('CIDSI','EOTELE'),
('CIDSS','EOTELE'),
('1EPHG','EOTELE'),
('EPHPU','EOTELE'),
('EPHSS','EOTELE'),
('PRNPS','EOTELE'),
('RIICO','EOTELE'),
('CIAPA','EOTELE'),
('1CIDG','EOTELE'),
('CXFSS','EOTELE'),
('CVNCI','EOTELE'),
('CVNGB','EOTELE'),
('CVNSN','EOTELE'),
('CVNSS','EOTELE'),
('EPHHL','EOTELE'),
('EPHMG','EOTELE'),
('FIUCA','EOTELE'),
('FIUSS','EOTELE'),
('FRAAN','EOTELE'),
('IATCA','EOTELE'),
('MABSD','EOTELE'),
('PRNDO','EOTELE'),
('PRNSS','EOTELE'),
('PYUCO','EOTELE'),
('RUBID','EOTELE'),
('RUBSS','EOTELE'),
('VITSS','EOTELE'),
('VITVI','EOTELE'),
('EPHCT','EOTELE'),
('LYUSS','EOTELE'),
('AIGLE','EOTELE'),
('ABAXA','EOTELE'),
('BAUKA','EOTELE'),
('BAUPU','EOTELE'),
('BAUSS','EOTELE'),
('BIXOR','EOTELE'),
('DATAR','EOTELE'),
('CRICO','EOTELE'),
('CRIHA','EOTELE'),
('CEAHY','EOTELE'),
('CLESS','EOTELE'),
('CVTSS','EOTELE'),
('CUUSS','EOTELE'),
('ERZES','EOTELE'),
('GOSHI','EOTELE'),
('HYEAR','EOTELE'),
('IPOSS','EOTELE'),
('KOTPA','EOTELE'),
('MEDPO','EOTELE'),
('MOASS','EOTELE'),
('OLVEU','EOTELE'),
('PIUED','EOTELE'),
('POPDE','EOTELE'),
('POPTM','EOTELE'),
('ROSSS','EOTELE'),
('TOPTU','EOTELE'),
('ABUMM','EOTELE'),
('ACAPT','EOTELE'),
('FRSCO','EOTELE'),
('AYHLA','EOTELE'),
('BOCAR','EOTELE'),
('BRLCC','EOTELE'),
('CEASS','EOTELE'),
('CEIAC','EOTELE'),
('ENCFR','EOTELE'),
('HAPSS','EOTELE'),
('HTTSS','EOTELE'),
('HAPHE','EOTELE'),
('MLPSS','EOTELE'),
('MIMAC','EOTELE'),
('MIMLA','EOTELE'),
('PIUCM','EOTELE'),
('PIUNE','EOTELE'),
('PIUPO','EOTELE'),
('QUESS','EOTELE'),
('SCPCA','EOTELE'),
('SOLEL','EOTELE'),
('SOLSS','EOTELE'),
('SPHAN','EOTELE'),
('SPHOR','EOTELE'),
('1TRFG','EOTELE'),
('ACACS','EOTELE'),
('XTHSP','EOTELE'),
('SOLTU','EPIXCU'),
('CPSAN','EPIXCU'),
('NIOTA','EPIXCU'),
('1PEUG','EPIXCU'),
('PEUAX','EPIXCU'),
('PEUHY','EPIXCU'),
('PHYAL','EPIXCU'),
('PHYPE','EPIXCU'),
('LYPES','EPIXCU'),
('SOLME','EPIXCU'),
('SOLPC','EPIXCU'),
('SOLRF','EPIXCU'),
('SOLTO','EPIXCU'),
('ATRBE','EPIXCU'),
('DATST','EPIXCU'),
('PHYAN','EPIXCU'),
('PHYLF','EPIXCU'),
('PHYPU','EPIXCU'),
('SOLAM','EPIXCU'),
('SOLCA','EPIXCU'),
('SOLDU','EPIXCU'),
('SOLMO','EPIXCU'),
('SOLNI','EPIXCU'),
('SOLPS','EPIXCU'),
('SOLRS','EPIXCU'),
('SOLTU','EPIXPP'),
('LYPES','EPIXPP'),
('SOLME','EPIXPP'),
('CHESS','EPIXPP'),
('DATST','EPIXPP'),
('SOLNI','EPIXPP'),
('SOLTR','EPIXPP'),
('SOLTU','EPIXSU'),
('CPSFR','EPIXSU'),
('PHYAF','EPIXSU'),
('LYPES','EPIXSU'),
('SOLME','EPIXSU'),
('DATIN','EPIXSU'),
('HSYNI','EPIXSU'),
('LKPNA','EPIXSU'),
('1LYUG','EPIXSU'),
('NICPH','EPIXSU'),
('NIOAL','EPIXSU'),
('NIOAT','EPIXSU'),
('PHYLO','EPIXSU'),
('PHYLF','EPIXSU'),
('PHYPU','EPIXSU'),
('SOLCA','EPIXSU'),
('SOLDU','EPIXSU'),
('SOLNI','EPIXSU'),
('SOLRS','EPIXSU'),
('SOLTR','EPIXSU'),
('SOLXN','EPIXSU'),
('SOLLU','EPIXSU'),
('CUUPE','EPIXSU'),
('SOLTU','EPIXTU'),
('ALGRO','EPIXTU'),
('ARWLA','EPIXTU'),
('BEAVX','EPIXTU'),
('BRSOX','EPIXTU'),
('CPSFR','EPIXTU'),
('CUMSA','EPIXTU'),
('1CUUG','EPIXTU'),
('CUUMA','EPIXTU'),
('DESPI','EPIXTU'),
('1HELG','EPIXTU'),
('HELAN','EPIXTU'),
('IPOSS','EPIXTU'),
('LACSA','EPIXTU'),
('MEDSA','EPIXTU'),
('MEUSS','EPIXTU'),
('NIOTA','EPIXTU'),
('1PEUG','EPIXTU'),
('PHSVX','EPIXTU'),
('PHYAF','EPIXTU'),
('RAPSR','EPIXTU'),
('RIBRU','EPIXTU'),
('LYPES','EPIXTU'),
('SOLME','EPIXTU'),
('SPQOL','EPIXTU'),
('CITLA','EPIXTU'),
('CUMME','EPIXTU'),
('AMARE','EPIXTU'),
('1AMBG','EPIXTU'),
('KCHSC','EPIXTU'),
('CHEAL','EPIXTU'),
('DATIN','EPIXTU'),
('DATST','EPIXTU'),
('IVAXA','EPIXTU'),
('1LYUG','EPIXTU'),
('NICPH','EPIXTU'),
('NIOAL','EPIXTU'),
('1PHYG','EPIXTU'),
('PHYLC','EPIXTU'),
('PHYLO','EPIXTU'),
('PHYLF','EPIXTU'),
('PHYIX','EPIXTU'),
('PHYPR','EPIXTU'),
('PHYPU','EPIXTU'),
('PHYSS','EPIXTU'),
('SINAR','EPIXTU'),
('SOLAM','EPIXTU'),
('SOLCA','EPIXTU'),
('SOLDU','EPIXTU'),
('SOLNI','EPIXTU'),
('SOLRS','EPIXTU'),
('SOLTR','EPIXTU'),
('SOLLU','EPIXTU'),
('TAROF','EPIXTU'),
('MABSD','ERWIAM'),
('PYUCO','ERWIAM'),
('PYUPY','ERWIAM'),
('PYUUS','ERWIAM'),
('AMEAL','ERWIAM'),
('AMECA','ERWIAM'),
('AMELA','ERWIAM'),
('1CNMG','ERWIAM'),
('CNMJA','ERWIAM'),
('1CTTG','ERWIAM'),
('CTTBU','ERWIAM'),
('CTTBX','ERWIAM'),
('CTTDA','ERWIAM'),
('CTTLA','ERWIAM'),
('CTTLU','ERWIAM'),
('CTTMI','ERWIAM'),
('CTTMO','ERWIAM'),
('CTTNG','ERWIAM'),
('CTTSA','ERWIAM'),
('CTTCR','ERWIAM'),
('CTTWT','ERWIAM'),
('1CSCG','ERWIAM'),
('CSCOX','ERWIAM'),
('CSCMO','ERWIAM'),
('CSCPR','ERWIAM'),
('CYDOB','ERWIAM'),
('EIOJA','ERWIAM'),
('1MABG','ERWIAM'),
('MABBA','ERWIAM'),
('MABCO','ERWIAM'),
('MSPGE','ERWIAM'),
('STVDA','ERWIAM'),
('PDCSI','ERWIAM'),
('1PYEG','ERWIAM'),
('PYECO','ERWIAM'),
('PYECN','ERWIAM'),
('1PYUG','ERWIAM'),
('PYUBE','ERWIAM'),
('PYUEL','ERWIAM'),
('RUBFR','ERWIAM'),
('RUBID','ERWIAM'),
('1SOUG','ERWIAM'),
('SOUAI','ERWIAM'),
('SOUAU','ERWIAM'),
('ABOME','ERWIAM'),
('CTTHO','ERWIAM'),
('FRAAN','ERWIAM'),
('MABFB','ERWIAM'),
('PRNAR','ERWIAM'),
('PRNCF','ERWIAM'),
('PRNDO','ERWIAM'),
('PRNSC','ERWIAM'),
('1ROSG','ERWIAM'),
('ROSCN','ERWIAM'),
('ROSRG','ERWIAM'),
('SPVPR','ERWIAM'),
('PYUBO','ERWIAM'),
('PYUPS','ERWIAM'),
('PYUSP','ERWIAM'),
('PIUAT','GIBBCI'),
('PIUCN','GIBBCI'),
('PIUDE','GIBBCI'),
('PIUEL','GIBBCI'),
('PIUHA','GIBBCI'),
('PIUMR','GIBBCI'),
('PIUNI','GIBBCI'),
('PIUPA','GIBBCI'),
('PIUPT','GIBBCI'),
('PIUPL','GIBBCI'),
('PIUPI','GIBBCI'),
('PIURA','GIBBCI'),
('PIUST','GIBBCI'),
('PIUSI','GIBBCI'),
('PIUTD','GIBBCI'),
('PIUTH','GIBBCI'),
('PIUVI','GIBBCI'),
('1PIUG','GIBBCI'),
('PIUGG','GIBBCI'),
('PSTME','GIBBCI'),
('BROCN','GIBBCI'),
('HOLLA','GIBBCI'),
('FESAR','GIBBCI'),
('IUGRE','ERSHMU'),
('IUGNI','ERSHMU'),
('IUGNI','GEOHMO'),
('1IUGG','GEOHMO'),
('IUGAI','GEOHMO'),
('IUGCA','GEOHMO'),
('IUGCI','GEOHMO'),
('IUGHI','GEOHMO'),
('IUGMA','GEOHMO'),
('IUGMN','GEOHMO'),
('IUGMI','GEOHMO'),
('IUGMO','GEOHMO'),
('IUGRE','GEOHMO'),
('1PTFG','GEOHMO'),
('PTFFR','GEOHMO'),
('PTFRH','GEOHMO'),
('PTFST','GEOHMO'),
('SOLTU','HETDPA'),
('2PLAN','HETDPA'),
('LYPES','HETDPA'),
('SOLME','HETDPA'),
('1SOLG','HETDPA'),
('SOLTU','HETDRO'),
('2PLAN','HETDRO'),
('LYPES','HETDRO'),
('SOLME','HETDRO'),
('1SOLG','HETDRO'),
('1VITG','PHYP64'),
('VITVI','PHYP64'),
('VITRI','PHYP64'),
('CLVVT','PHYP64'),
('CHYCA','PHYP64'),
('TRFRE','PHYP64'),
('VICFX','PHYP64'),
('CIDSI','HOMLTR'),
('MCDTE','HOMLTR'),
('PEBAM','HOMLTR'),
('1CIDG','HOMLTR'),
('1FRXG','HOMLTR'),
('LAEIN','HOMLTR'),
('MEDSA','HOMLTR'),
('NEROL','HOMLTR'),
('PRNDO','HOMLTR'),
('PRNDU','HOMLTR'),
('PRNPS','HOMLTR'),
('1RHUG','HOMLTR'),
('VITVI','HOMLTR'),
('LYPES','MELGCH'),
('SOLTU','MELGCH'),
('AVESA','MELGCH'),
('BEAVX','MELGCH'),
('DAUCS','MELGCH'),
('HORVX','MELGCH'),
('MEDSA','MELGCH'),
('PHSVX','MELGCH'),
('PIBSX','MELGCH'),
('1GRAF','MELGCH'),
('SCVHI','MELGCH'),
('TAROF','MELGCH'),
('TRZAX','MELGCH'),
('ZEAMX','MELGCH'),
('AATRA','MELGCH'),
('BEAVX','MELGFA'),
('DAUCS','MELGFA'),
('FRAAN','MELGFA'),
('HORVX','MELGFA'),
('LACSA','MELGFA'),
('LOLMU','MELGFA'),
('MEDSA','MELGFA'),
('LYPES','MELGFA'),
('SOLTU','MELGFA'),
('TRFRE','MELGFA'),
('ALLPO','MELGFA'),
('ASPOF','MELGFA'),
('CICIN','MELGFA'),
('CYUSC','MELGFA'),
('HEGSS','MELGFA'),
('DCTSP','MELGFA'),
('OEOER','MELGFA'),
('PHCTA','MELGFA'),
('SCVHI','MELGFA'),
('TRZAX','MELGFA'),
('AVESG','MELGFA'),
('LQTSS','MELGFA'),
('SOLNI','MELGFA'),
('SOLPS','MELGFA'),
('ORYSA','MELGGC'),
('TRZAX','MELGGC'),
('GLXMA','MELGGC'),
('ABMES','MELGGC'),
('ALLCE','MELGGC'),
('ALLFI','MELGGC'),
('ALLTU','MELGGC'),
('AVESA','MELGGC'),
('BEAVX','MELGGC'),
('BRSJU','MELGGC'),
('BRSOX','MELGGC'),
('BRSOB','MELGGC'),
('CPSAN','MELGGC'),
('CTURO','MELGGC'),
('CXSES','MELGGC'),
('CRGCA','MELGGC'),
('CORSA','MELGGC'),
('CUMSA','MELGGC'),
('CYGCI','MELGGC'),
('CYPFE','MELGGC'),
('ELECO','MELGGC'),
('FIMDP','MELGGC'),
('HORVX','MELGGC'),
('IPABA','MELGGC'),
('KYLGR','MELGGC'),
('LACSA','MELGGC'),
('LUDAC','MELGGC'),
('MUBAC','MELGGC'),
('OPLCO','MELGGC'),
('PANMI','MELGGC'),
('PESGL','MELGGC'),
('PEUSS','MELGGC'),
('PHSVX','MELGGC'),
('POXDR','MELGGC'),
('PIBSX','MELGGC'),
('POAAN','MELGGC'),
('POROL','MELGGC'),
('SACOF','MELGGC'),
('SETIT','MELGGC'),
('LYPES','MELGGC'),
('SOLME','MELGGC'),
('SOLTU','MELGGC'),
('SORVU','MELGGC'),
('SPQOL','MELGGC'),
('STEME','MELGGC'),
('VICFX','MELGGC'),
('PHSMU','MELGGC'),
('PHSAU','MELGGC'),
('VIGSI','MELGGC'),
('ZEAMX','MELGGC'),
('AGECO','MELGGC'),
('ALSPA','MELGGC'),
('1ALOG','MELGGC'),
('ALOCA','MELGGC'),
('AMASP','MELGGC'),
('AMAVI','MELGGC'),
('1ANOG','MELGGC'),
('1BLUG','MELGGC'),
('PANRA','MELGGC'),
('CLLAS','MELGGC'),
('COMBE','MELGGC'),
('VENCI','MELGGC'),
('CYNDA','MELGGC'),
('CYPDI','MELGGC'),
('CYPIM','MELGGC'),
('CYPIR','MELGGC'),
('CYPPI','MELGGC'),
('CYPPR','MELGGC'),
('CUOCY','MELGGC'),
('CYPPU','MELGGC'),
('CYPRO','MELGGC'),
('DEDTR','MELGGC'),
('DIGFI','MELGGC'),
('DIGLO','MELGGC'),
('DIGSA','MELGGC'),
('ECHCO','MELGGC'),
('ECHCG','MELGGC'),
('ECLAL','MELGGC'),
('ELEIN','MELGGC'),
('ERAAM','MELGGC'),
('EPHHI','MELGGC'),
('FIMCO','MELGGC'),
('FIMDI','MELGGC'),
('FIMLI','MELGGC'),
('FUICI','MELGGC'),
('GNAFA','MELGGC'),
('GNAPU','MELGGC'),
('GRACE','MELGGC'),
('HYODI','MELGGC'),
('1HRXG','MELGGC'),
('HETRE','MELGGC'),
('IMPCY','MELGGC'),
('ISCRU','MELGGC'),
('KYLBR','MELGGC'),
('LERHE','MELGGC'),
('LEVLA','MELGGC'),
('1LIDG','MELGGC'),
('1LUDG','MELGGC'),
('ANEKE','MELGGC'),
('MUDNU','MELGGC'),
('OXACO','MELGGC'),
('1PANG','MELGGC'),
('PANDI','MELGGC'),
('PANSU','MELGGC'),
('PANRE','MELGGC'),
('PASSC','MELGGC'),
('PESPE','MELGGC'),
('PYLUR','MELGGC'),
('MOOVA','MELGGC'),
('1RANG','MELGGC'),
('RANPU','MELGGC'),
('RNGPA','MELGGC'),
('SAEIN','MELGGC'),
('SCPAR','MELGGC'),
('SCFDU','MELGGC'),
('SOLNI','MELGGC'),
('SOLSI','MELGGC'),
('BOIAR','MELGGC'),
('1SPSG','MELGGC'),
('SPSSE','MELGGC'),
('SPDZE','MELGGC'),
('URNLO','MELGGC'),
('PANPU','MELGGC'),
('1ABIG','1MONCG'),
('1CEUG','1MONCG'),
('1LAXG','1MONCG'),
('1PIEG','1MONCG'),
('1PIUG','1MONCG'),
('PRNPS','PCMV00'),
('1PRNG','PCMV00'),
('PRNAR','PCMV00'),
('PRNBE','PCMV00'),
('PRNDO','PCMV00'),
('PRNDU','PCMV00'),
('PRNSC','PCMV00'),
('PRNSL','PCMV00'),
('PRNPS','PRMV00'),
('VITLA','PRMV00'),
('VITVI','PRMV00'),
('RUMCR','PRMV00'),
('SOLCA','PRMV00'),
('TAROF','PRMV00'),
('1CHES','PRMV00'),
('CHEQU','PRMV00'),
('1CUCF','PRMV00'),
('1LEGF','PRMV00'),
('1SOLF','PRMV00'),
('VACCO','PRMV00'),
('CIDLI','GUIGCI'),
('CIDSI','GUIGCI'),
('CJCWE','GUIGCI'),
('CIDAF','GUIGCI'),
('CIDAU','GUIGCI'),
('CIDGR','GUIGCI'),
('CIDME','GUIGCI'),
('CIDPA','GUIGCI'),
('CIDRE','GUIGCI'),
('CIDTK','GUIGCI'),
('CIDLO','GUIGCI'),
('CIDNO','GUIGCI'),
('1FOLG','GUIGCI'),
('1CIDG','GUIGCI'),
('1KAMG','PHYTRA'),
('KAMLA','PHYTRA'),
('LAXDE','PHYTRA'),
('LAXLE','PHYTRA'),
('LIADF','PHYTRA'),
('1PIRG','PHYTRA'),
('QUEAG','PHYTRA'),
('1RHOG','PHYTRA'),
('SYRVU','PHYTRA'),
('1VIBG','PHYTRA'),
('ABIAL','PHYTRA'),
('ABICO','PHYTRA'),
('ABIGR','PHYTRA'),
('ABIMA','PHYTRA'),
('ABIPR','PHYTRA'),
('ACRCJ','PHYTRA'),
('ACRDA','PHYTRA'),
('ACRLA','PHYTRA'),
('ACRMA','PHYTRA'),
('ACRPP','PHYTRA'),
('ADIAL','PHYTRA'),
('ADIJO','PHYTRA'),
('AECCA','PHYTRA'),
('AECHI','PHYTRA'),
('ALUCO','PHYTRA'),
('ARDME','PHYTRA'),
('ARDUN','PHYTRA'),
('ARYCA','PHYTRA'),
('ARYCO','PHYTRA'),
('ARYGL','PHYTRA'),
('ARYMA','PHYTRA'),
('ARYSE','PHYTRA'),
('ARYUU','PHYTRA'),
('ARYVR','PHYTRA'),
('ARYVD','PHYTRA'),
('ADAJA','PHYTRA'),
('MAHAQ','PHYTRA'),
('BETPE','PHYTRA'),
('CUNVU','PHYTRA'),
('CALOC','PHYTRA'),
('1CAHG','PHYTRA'),
('CAHJA','PHYTRA'),
('CAHSQ','PHYTRA'),
('CSNSA','PHYTRA'),
('CSOOR','PHYTRA'),
('CEATH','PHYTRA'),
('CCSCH','PHYTRA'),
('CHCLA','PHYTRA'),
('1COAG','PHYTRA'),
('COATE','PHYTRA'),
('CSOCH','PHYTRA'),
('CINCA','PHYTRA'),
('CJXAN','PHYTRA'),
('CRWCP','PHYTRA'),
('CRWHY','PHYTRA'),
('CRWKO','PHYTRA'),
('CYVSP','PHYTRA'),
('CYLCR','PHYTRA'),
('1CMYG','PHYTRA'),
('DPLGL','PHYTRA'),
('DSYMY','PHYTRA'),
('DRIWI','PHYTRA'),
('DYOAR','PHYTRA'),
('EUCHS','PHYTRA'),
('EUOKI','PHYTRA'),
('FAUSY','PHYTRA'),
('RHACA','PHYTRA'),
('RHAPU','PHYTRA'),
('FRXEX','PHYTRA'),
('FRXLA','PHYTRA'),
('GAREL','PHYTRA'),
('GAHPR','PHYTRA'),
('GAHSH','PHYTRA'),
('GRSLI','PHYTRA'),
('HAMMO','PHYTRA'),
('HAMVI','PHYTRA'),
('HAMIN','PHYTRA'),
('PHNAR','PHYTRA'),
('ILEAQ','PHYTRA'),
('ILECH','PHYTRA'),
('ILELF','PHYTRA'),
('KAMAN','PHYTRA'),
('LURNO','PHYTRA'),
('LUTAX','PHYTRA'),
('LUTFO','PHYTRA'),
('LIAGL','PHYTRA'),
('LONHS','PHYTRA'),
('LORCH','PHYTRA'),
('1MAGG','PHYTRA'),
('MAGAC','PHYTRA'),
('MAGKA','PHYTRA'),
('MAGDE','PHYTRA'),
('MAGDN','PHYTRA'),
('MIADO','PHYTRA'),
('MIAVI','PHYTRA'),
('MAGFO','PHYTRA'),
('MAGGR','PHYTRA'),
('MGTIN','PHYTRA'),
('MAGKO','PHYTRA'),
('MAGLI','PHYTRA'),
('MAGLT','PHYTRA'),
('MAGMD','PHYTRA'),
('MAGSA','PHYTRA'),
('MAGST','PHYTRA'),
('MAGWI','PHYTRA'),
('MAGLO','PHYTRA'),
('MAGSO','PHYTRA'),
('MAGTH','PHYTRA'),
('SMLRA','PHYTRA'),
('NEROL','PHYTRA'),
('NOFOB','PHYTRA'),
('1OSUG','PHYTRA'),
('OSUDC','PHYTRA'),
('OSUDE','PHYTRA'),
('OSUFR','PHYTRA'),
('OSUHE','PHYTRA'),
('OMRBE','PHYTRA'),
('PTTPE','PHYTRA'),
('PHNFR','PHYTRA'),
('PHPOP','PHYTRA'),
('PIESI','PHYTRA'),
('QKRMO','PHYTRA'),
('PIRFO','PHYTRA'),
('PIRHY','PHYTRA'),
('PIRJA','PHYTRA'),
('PTUUN','PHYTRA'),
('PRNLR','PHYTRA'),
('PRNLU','PHYTRA'),
('PSTME','PHYTRA'),
('PYEKO','PHYTRA'),
('1QUEG','PHYTRA'),
('QUEAC','PHYTRA'),
('QUECE','PHYTRA'),
('QUECH','PHYTRA'),
('QUEFC','PHYTRA'),
('QUEIL','PHYTRA'),
('QUEKE','PHYTRA'),
('QUEPS','PHYTRA'),
('QUEPE','PHYTRA'),
('QUEPI','PHYTRA'),
('QUERO','PHYTRA'),
('QUERU','PHYTRA'),
('RHOAB','PHYTRA'),
('RHOCW','PHYTRA'),
('RHOMC','PHYTRA'),
('RHOPO','PHYTRA'),
('RHOYA','PHYTRA'),
('RIBLF','PHYTRA'),
('1ROSG','PHYTRA'),
('ROSGY','PHYTRA'),
('ROSRG','PHYTRA'),
('RUBSP','PHYTRA'),
('SAXCP','PHYTRA'),
('1SARG','PHYTRA'),
('SHMAR','PHYTRA'),
('SHMWA','PHYTRA'),
('SEQSE','PHYTRA'),
('TAXBA','PHYTRA'),
('TAXBR','PHYTRA'),
('TAXME','PHYTRA'),
('TOYCA','PHYTRA'),
('RHUDI','PHYTRA'),
('TNTLA','PHYTRA'),
('TSUHE','PHYTRA'),
('UMBCA','PHYTRA'),
('1VACG','PHYTRA'),
('VACIN','PHYTRA'),
('VACMY','PHYTRA'),
('VACOV','PHYTRA'),
('VACVI','PHYTRA'),
('VAVPL','PHYTRA'),
('VIBDV','PHYTRA'),
('VIBHI','PHYTRA'),
('VIBPT','PHYTRA'),
('VIBTI','PHYTRA'),
('VIBBO','PHYTRA'),
('1VISG','PHYTRA'),
('1ARYG','PHYTRA'),
('CHAAN','PHYTRA'),
('EPICT','PHYTRA'),
('PTJCR','PHYTRA'),
('PIEGA','1PISOG'),
('PIEMA','1PISOG'),
('PIUBN','1PISOG'),
('1PIEG','1PISOG'),
('PIEAB','1PISOG'),
('PIEPU','1PISOG'),
('1PIUG','1PISOG'),
('PIUCA','1PISOG'),
('PIUCN','1PISOG'),
('PIUEC','1PISOG'),
('PIUEL','1PISOG'),
('PIUGL','1PISOG'),
('PIUPA','1PISOG'),
('PIUPG','1PISOG'),
('PIURA','1PISOG'),
('PIURE','1PISOG'),
('PIURI','1PISOG'),
('PIUSE','1PISOG'),
('PIUST','1PISOG'),
('PIUSI','1PISOG'),
('PIUTD','1PISOG'),
('PIUVI','1PISOG'),
('CEUAT','1PISOG'),
('CEUDE','1PISOG'),
('CEULI','1PISOG'),
('PIUMR','1PISOG'),
('IUGNI','PITOJU'),
('1IUGG','PITOJU'),
('IUGAI','PITOJU'),
('IUGCA','PITOJU'),
('IUGCT','PITOJU'),
('IUGCI','PITOJU'),
('IUGHI','PITOJU'),
('IUGMA','PITOJU'),
('IUGMN','PITOJU'),
('IUGMI','PITOJU'),
('IUGMO','PITOJU'),
('IUGRE','PITOJU'),
('1PTFG','PITOJU'),
('PTFFR','PITOJU'),
('PTFRH','PITOJU'),
('PTFST','PITOJU'),
('CYLAV','POPIJA'),
('GLXMA','POPIJA'),
('MABSD','POPIJA'),
('PHSVX','POPIJA'),
('PRNAR','POPIJA'),
('PRNAV','POPIJA'),
('PRNDO','POPIJA'),
('PRNPS','POPIJA'),
('PRNSN','POPIJA'),
('1ROSG','POPIJA'),
('VITVI','POPIJA'),
('1WSTG','POPIJA'),
('ZEAMX','POPIJA'),
('ACRPA','POPIJA'),
('ACRPL','POPIJA'),
('1ATIG','POPIJA'),
('AECHI','POPIJA'),
('ALGRO','POPIJA'),
('ALUGL','POPIJA'),
('ALUJA','POPIJA'),
('ALGOF','POPIJA'),
('AMCJA','POPIJA'),
('1ASPG','POPIJA'),
('ASPOF','POPIJA'),
('BEHRA','POPIJA'),
('BETPO','POPIJA'),
('CSNCR','POPIJA'),
('CSNDE','POPIJA'),
('CXEAL','POPIJA'),
('1CYPF','POPIJA'),
('DIUES','POPIJA'),
('POLCO','POPIJA'),
('FIIKA','POPIJA'),
('FRAAN','POPIJA'),
('1HIBG','POPIJA'),
('HIBPA','POPIJA'),
('HIBSY','POPIJA'),
('HUMLU','POPIJA'),
('HYPJA','POPIJA'),
('IUGNI','POPIJA'),
('KERJA','POPIJA'),
('LAEIN','POPIJA'),
('MABBA','POPIJA'),
('MABFB','POPIJA'),
('MALPU','POPIJA'),
('MEDSA','POPIJA'),
('MEIAZ','POPIJA'),
('OCIBA','POPIJA'),
('OEOBI','POPIJA'),
('1PRTG','POPIJA'),
('PRTQU','POPIJA'),
('POLLA','POPIJA'),
('POLOR','POPIJA'),
('POLPY','POPIJA'),
('PLTOR','POPIJA'),
('PLTHY','POPIJA'),
('1GRAF','POPIJA'),
('POPMA','POPIJA'),
('POPNT','POPIJA'),
('PRNCX','POPIJA'),
('PRNCE','POPIJA'),
('PRNJP','POPIJA'),
('PRNPN','POPIJA'),
('PRNSC','POPIJA'),
('PRNSO','POPIJA'),
('PRNSL','POPIJA'),
('PTEAQ','POPIJA'),
('QUEAS','POPIJA'),
('QUEVB','POPIJA'),
('RHERP','POPIJA'),
('ROBPS','POPIJA'),
('ROSMU','POPIJA'),
('RUBCR','POPIJA'),
('1RUMG','POPIJA'),
('SAXDI','POPIJA'),
('SAXVI','POPIJA'),
('SSAAL','POPIJA'),
('SMICH','POPIJA'),
('LYPES','POPIJA'),
('SOLME','POPIJA'),
('SOUAM','POPIJA'),
('TILAM','POPIJA'),
('TILCO','POPIJA'),
('TILJA','POPIJA'),
('TILMI','POPIJA'),
('TOXQU','POPIJA'),
('TRFPR','POPIJA'),
('ULMAM','POPIJA'),
('ULMPA','POPIJA'),
('ULMPR','POPIJA'),
('1VACG','POPIJA'),
('VACCO','POPIJA'),
('VITAE','POPIJA'),
('VITFL','POPIJA'),
('VITLA','POPIJA'),
('WSTFL','POPIJA'),
('ZELSE','POPIJA'),
('POLCU','POPIJA'),
('1OEOG','POPIJA'),
('1URTG','POPIJA'),
('ATICH','PSDMAK'),
('ATIDE','PSDMAK'),
('1ATIG','PSDMAK'),
('ATIAR','PSDMAK'),
('ATIKO','PSDMAK'),
('ALRPH','PSDMAK'),
('PAZTO','PSDMAK'),
('SETVI','PSDMAK'),
('1EUCG','RALSSL'),
('2PLAN','RALSSL'),
('RUBID','RLCV00'),
('RUBOC','RLCV00'),
('RUBSG','RLCV00'),
('1RUBG','RLCV00'),
('RUBAL','RLCV00'),
('RUBNG','RLCV00'),
('RUBPH','RLCV00'),
('MABSD','RHAGPO'),
('CTTAP','RHAGPO'),
('CTTIT','RHAGPO'),
('CTTLA','RHAGPO'),
('CSCCG','RHAGPO'),
('PRNAN','RHAGPO'),
('PRNAR','RHAGPO'),
('PRNAV','RHAGPO'),
('PRNCF','RHAGPO'),
('PRNCE','RHAGPO'),
('PRNDO','RHAGPO'),
('PRNEM','RHAGPO'),
('PRNPS','RHAGPO'),
('PRNSC','RHAGPO'),
('PYUCO','RHAGPO'),
('PYUPY','RHAGPO'),
('SOUAU','RHAGPO'),
('SOUSO','RHAGPO'),
('MABFB','RHAGPO'),
('PRNMH','RHAGPO'),
('PYEAN','RHAGPO'),
('ROSRG','RHAGPO'),
('ROSVI','RHAGPO'),
('CSCPU','RHAGPO'),
('PRNVG','RHAGPO'),
('ABOAR','RHAGPO'),
('1CSCG','RHAGPO'),
('CSCAE','RHAGPO'),
('CSCDO','RHAGPO'),
('CSCFL','RHAGPO'),
('CSCHO','RHAGPO'),
('CSCOX','RHAGPO'),
('CSCMA','RHAGPO'),
('CSCMS','RHAGPO'),
('CSCME','RHAGPO'),
('CSCML','RHAGPO'),
('CSCMO','RHAGPO'),
('CSCOP','RHAGPO'),
('CSCVI','RHAGPO'),
('PRNAM','RHAGPO'),
('PRNUM','RHAGPO'),
('ROSBA','RRV000'),
('ROSBC','RRV000'),
('ROSMU','RRV000'),
('ROSRB','RRV000'),
('ROSRG','RRV000'),
('ROSVL','RRV000'),
('ROSWO','RRV000'),
('ROSOD','RRV000'),
('1ROSG','RRV000'),
('ROSAS','RRV000'),
('ROSCN','RRV000'),
('ROSCF','RRV000'),
('ROSGL','RRV000'),
('ROSNU','RRV000'),
('ROSPI','RRV000'),
('ROSPP','RRV000'),
('1VITG','SCAPLI'),
('CIDSI','SCITAU'),
('1CJCG','SCITAU'),
('1CIDG','SCITAU'),
('CIDLI','SCITAU'),
('CIDPA','SCITAU'),
('CIDRE','SCITAU'),
('1FOLG','SCITAU'),
('MNGIN','SCITAU'),
('PMITR','SCITAU'),
('CJFMI','SCITAU'),
('PEBAM','SCITAU'),
('ARHHY','SCITAU'),
('1ASPG','SCITAU'),
('1GOSG','SCITAU'),
('MUBPA','SCITAU'),
('RIICO','SCITAU'),
('VITVI','SCITAU'),
('1ACAG','SCITAU'),
('1COGG','SCITAU'),
('CIDCL','SCITCI'),
('CIDLI','SCITCI'),
('CIDPA','SCITCI'),
('CIDRE','SCITCI'),
('CIDSI','SCITCI'),
('CIDUN','SCITCI'),
('1CJCG','SCITCI'),
('1CIDG','SCITCI'),
('1FOLG','SCITCI'),
('PMITR','SCITCI'),
('CJFMI','SCITCI'),
('VACCO','SCITCI'),
('CYAIL','SCITCI'),
('GOSHI','SCITCI'),
('1MAGG','SCITCI'),
('MEDSA','SCITCI'),
('PHXDA','SCITCI'),
('1ROSG','SCITCI'),
('VITVI','SCITCI'),
('1QUEG','SCITCI'),
('RHULU','SCITCI'),
('GLXMA','LAPHFR'),
('GOSHI','LAPHFR'),
('ORYSA','LAPHFR'),
('SACOF','LAPHFR'),
('SORVU','LAPHFR'),
('ZEAMX','LAPHFR'),
('ABMES','LAPHFR'),
('ACAMR','LAPHFR'),
('ACCSS','LAPHFR'),
('ACNHI','LAPHFR'),
('AGECO','LAPHFR'),
('AGSGI','LAPHFR'),
('AGSHI','LAPHFR'),
('AGSST','LAPHFR'),
('ALGRO','LAPHFR'),
('ALLCE','LAPHFR'),
('ALLFI','LAPHFR'),
('ALLSA','LAPHFR'),
('ALFVE','LAPHFR'),
('ALRFI','LAPHFR'),
('AMADU','LAPHFR'),
('AMACH','LAPHFR'),
('AMAQU','LAPHFR'),
('AMASP','LAPHFR'),
('AMAVI','LAPHFR'),
('ANOLE','LAPHFR'),
('ANOVI','LAPHFR'),
('ARHHY','LAPHFR'),
('ARHPI','LAPHFR'),
('ASCSS','LAPHFR'),
('ASPOF','LAPHFR'),
('ASLNI','LAPHFR'),
('ASTSS','LAPHFR'),
('ATRBE','LAPHFR'),
('AVEBY','LAPHFR'),
('AVESA','LAPHFR'),
('AVESG','LAPHFR'),
('AXOCO','LAPHFR'),
('AXOAF','LAPHFR'),
('BACDR','LAPHFR'),
('BACNE','LAPHFR'),
('BEGRE','LAPHFR'),
('BEAVX','LAPHFR'),
('BEAVV','LAPHFR'),
('BIDAL','LAPHFR'),
('BIDPI','LAPHFR'),
('BOEER','LAPHFR'),
('BOILF','LAPHFR'),
('ANOPE','LAPHFR'),
('BRAPL','LAPHFR'),
('BRAPP','LAPHFR'),
('PANRA','LAPHFR'),
('BRSNN','LAPHFR'),
('BRSOB','LAPHFR'),
('BRSOL','LAPHFR'),
('BRSOA','LAPHFR'),
('BRSRR','LAPHFR'),
('BRZLA','LAPHFR'),
('BRZMI','LAPHFR'),
('BROCA','LAPHFR'),
('DATCA','LAPHFR'),
('CAJCA','LAPHFR'),
('CLDOF','LAPHFR'),
('CMPSS','LAPHFR'),
('CNAEN','LAPHFR'),
('CPSAN','LAPHFR'),
('CRUSS','LAPHFR'),
('CRXSS','LAPHFR'),
('CIAPA','LAPHFR'),
('CISSS','LAPHFR'),
('CAUTI','LAPHFR'),
('CYAIL','LAPHFR'),
('CEOAR','LAPHFR'),
('CETIN','LAPHFR'),
('PESCL','LAPHFR'),
('CCHEC','LAPHFR'),
('PESPU','LAPHFR'),
('CCHPA','LAPHFR'),
('CCHTR','LAPHFR'),
('CEEHI','LAPHFR'),
('CMEHU','LAPHFR'),
('CHEAL','LAPHFR'),
('CHEQU','LAPHFR'),
('CHRBA','LAPHFR'),
('CHRGA','LAPHFR'),
('CSQLO','LAPHFR'),
('CIEAR','LAPHFR'),
('CICEN','LAPHFR'),
('CICIN','LAPHFR'),
('ZIUCA','LAPHFR'),
('CITLA','LAPHFR'),
('CIDAU','LAPHFR'),
('CIDLI','LAPHFR'),
('CIDPA','LAPHFR'),
('CIDRE','LAPHFR'),
('CIDSI','LAPHFR'),
('CIDUN','LAPHFR'),
('CCNNU','LAPHFR'),
('CDIVA','LAPHFR'),
('COFAR','LAPHFR'),
('COMBE','LAPHFR'),
('COMDI','LAPHFR'),
('COMER','LAPHFR'),
('CONAR','LAPHFR'),
('CRGCA','LAPHFR'),
('CRGOL','LAPHFR'),
('CORSA','LAPHFR'),
('CDTSE','LAPHFR'),
('CVTBR','LAPHFR'),
('CVTJU','LAPHFR'),
('CVTSP','LAPHFR'),
('CVNCP','LAPHFR'),
('CUMME','LAPHFR'),
('CUMSA','LAPHFR'),
('CUUMI','LAPHFR'),
('CUUMA','LAPHFR'),
('CUUPE','LAPHFR'),
('CYDOB','LAPHFR'),
('CYUCA','LAPHFR'),
('CYUSC','LAPHFR'),
('CYNDA','LAPHFR'),
('CYNNL','LAPHFR'),
('CYNPL','LAPHFR'),
('CYPCP','LAPHFR'),
('CYPES','LAPHFR'),
('CYPPA','LAPHFR'),
('CYPRT','LAPHFR'),
('CYPRO','LAPHFR'),
('CYPSF','LAPHFR'),
('DTTAE','LAPHFR'),
('DAHPI','LAPHFR'),
('DAUCA','LAPHFR'),
('DAUPU','LAPHFR'),
('CHYHO','LAPHFR'),
('DEDAD','LAPHFR'),
('DINCA','LAPHFR'),
('DIHAR','LAPHFR'),
('DIGAG','LAPHFR'),
('DIGAD','LAPHFR'),
('DIGCN','LAPHFR'),
('DIGER','LAPHFR'),
('DIGHO','LAPHFR'),
('DIGIS','LAPHFR'),
('DIGPD','LAPHFR'),
('DIGSA','LAPHFR'),
('DIGSW','LAPHFR'),
('DOSKA','LAPHFR'),
('ECHCO','LAPHFR'),
('ECHCG','LAPHFR'),
('EAIGU','LAPHFR'),
('ELECO','LAPHFR'),
('ELEIN','LAPHFR'),
('ELETR','LAPHFR'),
('AGRRE','LAPHFR'),
('ERAAI','LAPHFR'),
('EREHI','LAPHFR'),
('EREVA','LAPHFR'),
('ERLOP','LAPHFR'),
('ERICA','LAPHFR'),
('ERBPO','LAPHFR'),
('ERXFO','LAPHFR'),
('ERXHR','LAPHFR'),
('ERXME','LAPHFR'),
('EUCCM','LAPHFR'),
('EUCRO','LAPHFR'),
('EUCUP','LAPHFR'),
('ESTDI','LAPHFR'),
('FAGES','LAPHFR'),
('FESAV','LAPHFR'),
('FEVCO','LAPHFR'),
('FIUCA','LAPHFR'),
('FIMLI','LAPHFR'),
('FRACH','LAPHFR'),
('FRAVE','LAPHFR'),
('FRAAN','LAPHFR'),
('GERSS','LAPHFR'),
('GEBJA','LAPHFR'),
('GLAGA','LAPHFR'),
('HELAN','LAPHFR'),
('HEMAL','LAPHFR'),
('HVEBR','LAPHFR'),
('HIBCA','LAPHFR'),
('HORVX','LAPHFR'),
('ILEPA','LAPHFR'),
('IPAWA','LAPHFR'),
('IPOAQ','LAPHFR'),
('IPOBA','LAPHFR'),
('IPOGF','LAPHFR'),
('PHBPU','LAPHFR'),
('IPOTR','LAPHFR'),
('IATCU','LAPHFR'),
('IUGRE','LAPHFR'),
('LESST','LAPHFR'),
('LACSA','LAPHFR'),
('1LAEG','LAPHFR'),
('LEECO','LAPHFR'),
('LECHE','LAPHFR'),
('COPDI','LAPHFR'),
('LEFFI','LAPHFR'),
('LESBI','LAPHFR'),
('LESTH','LAPHFR'),
('LIUUT','LAPHFR'),
('LOLMU','LAPHFR'),
('LUFAE','LAPHFR'),
('LUPAL','LAPHFR'),
('MLPGL','LAPHFR'),
('MABSD','LAPHFR'),
('MNGIN','LAPHFR'),
('MANES','LAPHFR'),
('MARAR','LAPHFR'),
('MARLE','LAPHFR'),
('MEDSA','LAPHFR'),
('PANMA','LAPHFR'),
('MLCBI','LAPHFR'),
('MEUOF','LAPHFR'),
('MILMI','LAPHFR'),
('RHYRE','LAPHFR'),
('MLSOF','LAPHFR'),
('MIBJA','LAPHFR'),
('MISGI','LAPHFR'),
('MTCVI','LAPHFR'),
('MUCDE','LAPHFR'),
('MUESA','LAPHFR'),
('MUBPA','LAPHFR'),
('NIOTA','LAPHFR'),
('OCIBA','LAPHFR'),
('ONMVI','LAPHFR'),
('ORYLA','LAPHFR'),
('OXADV','LAPHFR'),
('OXAAM','LAPHFR'),
('PADSS','LAPHFR'),
('PANDI','LAPHFR'),
('PANLX','LAPHFR'),
('PANMI','LAPHFR'),
('PANVI','LAPHFR'),
('WEDGL','LAPHFR'),
('PASCO','LAPHFR'),
('PASCM','LAPHFR'),
('PASDI','LAPHFR'),
('PASDS','LAPHFR'),
('PASEX','LAPHFR'),
('PASFI','LAPHFR'),
('PASNO','LAPHFR'),
('PASPM','LAPHFR'),
('PASLL','LAPHFR'),
('PASUR','LAPHFR'),
('PASVA','LAPHFR'),
('PAQAA','LAPHFR'),
('PAQED','LAPHFR'),
('PAQLA','LAPHFR'),
('PVACA','LAPHFR'),
('PELZO','LAPHFR'),
('PESGL','LAPHFR'),
('PEBAM','LAPHFR'),
('PHAAN','LAPHFR'),
('PHACA','LAPHFR'),
('PHSLU','LAPHFR'),
('PHSVX','LAPHFR'),
('PIOCD','LAPHFR'),
('PHLPR','LAPHFR'),
('PHXRO','LAPHFR'),
('PHTSS','LAPHFR'),
('PIUCB','LAPHFR'),
('PIPSS','LAPHFR'),
('PIBSX','LAPHFR'),
('PTUTO','LAPHFR'),
('PLATO','LAPHFR'),
('PLTOC','LAPHFR'),
('PLIRU','LAPHFR'),
('POAAN','LAPHFR'),
('POAPR','LAPHFR'),
('EICCR','LAPHFR'),
('POROL','LAPHFR'),
('PRNPS','LAPHFR'),
('PSIGU','LAPHFR'),
('PUELO','LAPHFR'),
('PYUCO','LAPHFR'),
('RAPRA','LAPHFR'),
('RAPSR','LAPHFR'),
('RCHGR','LAPHFR'),
('RIICO','LAPHFR'),
('ROSSS','LAPHFR'),
('RUMCR','LAPHFR'),
('ERNAN','LAPHFR'),
('FESAR','LAPHFR'),
('ANOTN','LAPHFR'),
('SECCE','LAPHFR'),
('SEHED','LAPHFR'),
('SENBR','LAPHFR'),
('CASOB','LAPHFR'),
('SEGIN','LAPHFR'),
('SETIT','LAPHFR'),
('SETGE','LAPHFR'),
('SETVI','LAPHFR'),
('SIDCO','LAPHFR'),
('SIDRH','LAPHFR'),
('SIDPA','LAPHFR'),
('SOLAE','LAPHFR'),
('SOLDU','LAPHFR'),
('LYPES','LAPHFR'),
('SOLMA','LAPHFR'),
('SOLME','LAPHFR'),
('SOLSI','LAPHFR'),
('SOLTU','LAPHFR'),
('SONOL','LAPHFR'),
('SORAR','LAPHFR'),
('SORHA','LAPHFR'),
('SORSU','LAPHFR'),
('SGLPL','LAPHFR'),
('SPQOL','LAPHFR'),
('SPZIN','LAPHFR'),
('STCDI','LAPHFR'),
('STPSE','LAPHFR'),
('STYGN','LAPHFR'),
('TALPA','LAPHFR'),
('CHYCI','LAPHFR'),
('TAROF','LAPHFR'),
('TEMCA','LAPHFR'),
('THAGE','LAPHFR'),
('THOCA','LAPHFR'),
('TRAPA','LAPHFR'),
('TROPS','LAPHFR'),
('TRTPO','LAPHFR'),
('TRFIN','LAPHFR'),
('TRFPO','LAPHFR'),
('TRFPR','LAPHFR'),
('TRFRE','LAPHFR'),
('TRZAX','LAPHFR'),
('URAAU','LAPHFR'),
('UROAR','LAPHFR'),
('BRABR','LAPHFR'),
('BRARU','LAPHFR'),
('PANFA','LAPHFR'),
('PANPU','LAPHFR'),
('PANTE','LAPHFR'),
('VACCO','LAPHFR'),
('VACMA','LAPHFR'),
('VACOX','LAPHFR'),
('VESVI','LAPHFR'),
('ALEFO','LAPHFR'),
('VICFX','LAPHFR'),
('VIGSI','LAPHFR'),
('VIGSC','LAPHFR'),
('VIOSS','LAPHFR'),
('VITVI','LAPHFR'),
('WSTSI','LAPHFR'),
('XANSI','LAPHFR'),
('UCCEP','LAPHFR'),
('EUHME','LAPHFR'),
('ZEBPE','LAPHFR'),
('ZINOF','LAPHFR'),
('ZOYSS','LAPHFR'),
('FRAAN','SYWB00'),
('1FRAG','SYWB00'),
('SOLTU','SYNCEN'),
('1SOLG','SYNCEN'),
('DATME','SYNCEN'),
('SOLSS','SYNCEN'),
('DUBSS','SYNCEN'),
('HSYSS','SYNCEN'),
('LYUSS','SYNCEN'),
('NICSS','SYNCEN'),
('PHYAF','SYNCEN'),
('SZTSS','SYNCEN'),
('SOLDU','SYNCEN'),
('LYPES','SYNCEN'),
('SOLPC','SYNCEN'),
('SOLTU','TECASO'),
('2PLAN','1TEPHF'),
('CPSAN','ARGPLE'),
('CPSCH','ARGPLE'),
('CIDPA','ARGPLE'),
('CIDRE','ARGPLE'),
('CIDSI','ARGPLE'),
('GOSHI','ARGPLE'),
('LIHCH','ARGPLE'),
('MCDIN','ARGPLE'),
('MCDTE','ARGPLE'),
('MNGIN','ARGPLE'),
('PEBAM','ARGPLE'),
('PRNPS','ARGPLE'),
('PUNGR','ARGPLE'),
('QUERO','ARGPLE'),
('RIICO','ARGPLE'),
('SOLME','ARGPLE'),
('VITVI','ARGPLE'),
('ZEAMX','ARGPLE'),
('1CPSG','ARGPLE'),
('1CIDG','ARGPLE'),
('CIDLI','ARGPLE'),
('1GOSG','ARGPLE'),
('1PHSG','ARGPLE'),
('1ROSG','ARGPLE'),
('1VITG','ARGPLE'),
('SYZPA','ARGPLE'),
('ABMES','ARGPLE'),
('ABUHY','ARGPLE'),
('FEJSE','ARGPLE'),
('ANHCO','ARGPLE'),
('ANUMU','ARGPLE'),
('AVRCA','ARGPLE'),
('CAHJA','ARGPLE'),
('CAHSI','ARGPLE'),
('CEIPE','ARGPLE'),
('COFAR','ARGPLE'),
('DOSKA','ARGPLE'),
('EIOJA','ARGPLE'),
('EUEUN','ARGPLE'),
('IUGRE','ARGPLE'),
('MUBPA','ARGPLE'),
('MYCCA','ARGPLE'),
('OLVEU','ARGPLE'),
('PSICA','ARGPLE'),
('PSIFR','ARGPLE'),
('PSIGU','ARGPLE'),
('1QUEG','ARGPLE'),
('1SORG','ARGPLE'),
('SYZCD','ARGPLE'),
('SYZGG','ARGPLE'),
('SYZJA','ARGPLE'),
('SYZSA','ARGPLE'),
('THOCA','ARGPLE'),
('VIGSI','ARGPLE'),
('TRZAX','NEOVIN'),
('SECCE','NEOVIN'),
('1TRZG','NEOVIN'),
('TRZDU','NEOVIN'),
('TTLSS','NEOVIN'),
('AEGGE','NEOVIN'),
('1BROG','NEOVIN'),
('1LOLG','NEOVIN'),
('ORZMI','NEOVIN'),
('TRZDI','NEOVIN'),
('CPSAN','TOBRFV'),
('LYPES','TOBRFV'),
('1CPSG','TOBRFV'),
('SOLME','TOBRFV'),
('CHEMU','TOBRFV'),
('CHEGI','TOBRFV'),
('CHEQU','TOBRFV'),
('NIOBE','TOBRFV'),
('NIOCL','TOBRFV'),
('NIOGT','TOBRFV'),
('NIOTA','TOBRFV'),
('PEUHY','TOBRFV'),
('SOLNI','TOBRFV'),
('ABMES','TOLCND'),
('BNCHI','TOLCND'),
('CPSAN','TOLCND'),
('CPSFR','TOLCND'),
('CITLA','TOLCND'),
('CUMME','TOLCND'),
('CUMMF','TOLCND'),
('CUMSA','TOLCND'),
('CUUMA','TOLCND'),
('CUUMO','TOLCND'),
('CUUPE','TOLCND'),
('CUUPG','TOLCND'),
('LGNSI','TOLCND'),
('LUFAE','TOLCND'),
('MOMCH','TOLCND'),
('MOMTU','TOLCND'),
('LYPES','TOLCND'),
('TTHCU','TOLCND'),
('GLXMA','TOLCND'),
('GOSHI','TOLCND'),
('1IATG','TOLCND'),
('SOLME','TOLCND'),
('SOLTU','TOLCND'),
('CITFI','TOLCND'),
('CPSCH','TOLCND'),
('CTURO','TOLCND'),
('CEMNO','TOLCND'),
('CHYIN','TOLCND'),
('CMOTE','TOLCND'),
('DAHPI','TOLCND'),
('IASMU','TOLCND'),
('LUFAC','TOLCND'),
('PTNHY','TOLCND'),
('SRPAN','TOLCND'),
('SEHED','TOLCND'),
('TAGER','TOLCND'),
('PHSAU','TOLCND'),
('CIAPA','TOLCND'),
('CSDIN','TOLCND'),
('DAUCA','TOLCND'),
('HIBCA','TOLCND'),
('PAPSO','TOLCND'),
('ACCIN','TOLCND'),
('CTRPR','TOLCND'),
('CHEAL','TOLCND'),
('CHEGI','TOLCND'),
('COMBE','TOLCND'),
('CONAR','TOLCND'),
('DATST','TOLCND'),
('ECAEL','TOLCND'),
('ECLAL','TOLCND'),
('EPHHI','TOLCND'),
('PYLNI','TOLCND'),
('PHYMI','TOLCND'),
('RUMDE','TOLCND'),
('SOLNI','TOLCND'),
('SONOL','TOLCND'),
('TRFRE','TOLCND'),
('CUUEC','TOLCND'),
('CUUFO','TOLCND'),
('CUUFR','TOLCND'),
('CUUMZ','TOLCND'),
('CIDLI','TOXOCI'),
('CIDPA','TOXOCI'),
('CIDRE','TOXOCI'),
('CIDSI','TOXOCI'),
('1CJCG','TOXOCI'),
('1CIDG','TOXOCI'),
('1FOLG','TOXOCI'),
('PMITR','TOXOCI'),
('CJFMI','TOXOCI'),
('1CJCG','TRIZER'),
('1CIDG','TRIZER'),
('CIDAF','TRIZER'),
('CIDDE','TRIZER'),
('CIDJA','TRIZER'),
('CIDLI','TRIZER'),
('CIDGR','TRIZER'),
('CIDME','TRIZER'),
('CIDPA','TRIZER'),
('CIDRE','TRIZER'),
('CIDSI','TRIZER'),
('CIDNO','TRIZER'),
('1FOLG','TRIZER'),
('PMITR','TRIZER'),
('1RUTF','TRIZER'),
('CJFMI','TRIZER'),
('CSJED','TRIZER'),
('COATE','TRIZER'),
('CIDTG','TRIZER'),
('CIDUN','TRIZER'),
('MUYPA','TRIZER'),
('MUYKO','TRIZER'),
('1VEPG','TRIZER'),
('VEPNO','TRIZER'),
('CDDCA','TRIZER'),
('CIDAC','TRIZER'),
('TDDAS','TRIZER'),
('CUSAN','TRIZER'),
('VEPUN','TRIZER'),
('ZANSS','TRIZER'),
('1CIDG','XANTAU'),
('CIDAF','XANTCI'),
('CIDPA','XANTCI'),
('PMITR','XANTCI'),
('1CJCG','XANTCI'),
('1CIDG','XANTCI'),
('CIDAU','XANTCI'),
('CIDJU','XANTCI'),
('CIDLA','XANTCI'),
('CIDLI','XANTCI'),
('CIDMA','XANTCI'),
('CIDGR','XANTCI'),
('CIDME','XANTCI'),
('CIDRE','XANTCI'),
('CIDSI','XANTCI'),
('CIDUN','XANTCI'),
('1FOLG','XANTCI'),
('FOLJA','XANTCI'),
('1RUTF','XANTCI'),
('CJFMI','XANTCI'),
('SEVBU','XANTCI'),
('CIDDP','XANTCI'),
('FOLMA','XANTCI'),
('LNIDO','XANTCI'),
('SWNGL','XANTCI'),
('ALLSA','DITYDE'),
('BEAVX','DITYDE'),
('1CVOG','DITYDE'),
('DAHHY','DITYDE'),
('DAUCS','DITYDE'),
('1GLAG','DITYDE'),
('GLAHY','DITYDE'),
('1HYAG','DITYDE'),
('IRIHO','DITYDE'),
('SOLTU','DITYDE'),
('TIGPA','DITYDE'),
('1TRFG','DITYDE'),
('TULHY','DITYDE'),
('1ROSG','PHYCFR'),
('ROSAS','PHYCFR'),
('ROSCL','PHYCFR'),
('ROSCP','PHYCFR'),
('ROSFL','PHYCFR'),
('ROSGL','PHYCFR'),
('ROSMU','PHYCFR'),
('ROSNI','PHYCFR'),
('ROSPA','PHYCFR'),
('ROSRX','PHYCFR'),
('ROSRB','PHYCFR'),
('ROSRG','PHYCFR'),
('ROSSG','PHYCFR'),
('ROSVI','PHYCFR'),
('ROSWO','PHYCFR'),
('ABESS','HALYHA'),
('ACRSS','HALYHA'),
('AILAL','HALYHA'),
('ASPSS','HALYHA'),
('BUDDA','HALYHA'),
('CPSAN','HALYHA'),
('CTLSS','HALYHA'),
('CCSCA','HALYHA'),
('CIDSS','HALYHA'),
('CLQSS','HALYHA'),
('CMYJA','HALYHA'),
('CUMSA','HALYHA'),
('CVBSS','HALYHA'),
('DOSSS','HALYHA'),
('GLXMA','HALYHA'),
('HIBSS','HALYHA'),
('HIBSY','HALYHA'),
('IUGNI','HALYHA'),
('LONSS','HALYHA'),
('LYUHA','HALYHA'),
('MABSD','HALYHA'),
('MORSS','HALYHA'),
('ORYSA','HALYHA'),
('PAZSS','HALYHA'),
('PHSVX','HALYHA'),
('PRNAR','HALYHA'),
('PRNAV','HALYHA'),
('PRNDO','HALYHA'),
('PRNPS','HALYHA'),
('PYUCO','HALYHA'),
('ROSRG','HALYHA'),
('RUBID','HALYHA'),
('SAXSS','HALYHA'),
('LYPES','HALYHA'),
('SOLME','HALYHA'),
('1VACG','HALYHA'),
('VITVI','HALYHA'),
('ZEAMX','HALYHA'),
('1VITG','GRBAV0'),
('VITAE','GRBAV0'),
('VITAM','GRBAV0'),
('VITBI','GRBAV0'),
('VITBC','GRBAV0'),
('VITBL','GRBAV0'),
('VITMO','GRBAV0'),
('VITNE','GRBAV0'),
('VITVI','GRBAV0'),
('1VITG','GGVA00'),
('VITVI','GGVA00'),
('1VITG','GINV00'),
('VITVI','GINV00'),
('1PRNG','PPV000'),
('PRNAM','PPV000'),
('PRNAR','PPV000'),
('PRNAV','PPV000'),
('PRNBE','PPV000'),
('PRNBR','PPV000'),
('PRNCF','PPV000'),
('PRNCE','PPV000'),
('PRNCU','PPV000'),
('PRNDO','PPV000'),
('PRNDT','PPV000'),
('PRNDI','PPV000'),
('PRNDU','PPV000'),
('PRNGL','PPV000'),
('PRNHL','PPV000'),
('PRNIC','PPV000'),
('PRNJP','PPV000'),
('PRNLR','PPV000'),
('PRNMH','PPV000'),
('PRNMN','PPV000'),
('PRNMR','PPV000'),
('PRNMM','PPV000'),
('PRNNI','PPV000'),
('PRNPS','PPV000'),
('PRNPU','PPV000'),
('PRNSC','PPV000'),
('PRNSO','PPV000'),
('PRNSL','PPV000'),
('PRNSB','PPV000'),
('PRNSI','PPV000'),
('PRNSN','PPV000'),
('PRNTO','PPV000'),
('PRNTR','PPV000'),
('PRNVG','PPV000'),
('PRNBL','PPV000'),
('PRNCI','PPV000'),
('1DAHG','PHYPMA'),
('FOSSU','PHYPMA'),
('LILHY','PHYPMA'),
('1MABG','PHYPMA'),
('MABSD','PHYPMA'),
('PRNAV','PHYPMA'),
('PRNCE','PHYPMA'),
('PYUCO','PHYPMA'),
('SPVVH','PHYPMA'),
('VIBLA','PHYPMA'),
('TYHSS','POMASP'),
('ALLCE','DITYDI'),
('ALLPO','DITYDI'),
('ALLSA','DITYDI'),
('ALLSC','DITYDI'),
('APUGV','DITYDI'),
('AVESA','DITYDI'),
('BEAVX','DITYDI'),
('BRSNN','DITYDI'),
('CDSCU','DITYDI'),
('CVOFL','DITYDI'),
('1DING','DITYDI'),
('FRAAN','DITYDI'),
('GAXNI','DITYDI'),
('HELAN','DITYDI'),
('1HYAG','DITYDI'),
('HYAOR','DITYDI'),
('HYEMA','DITYDI'),
('HMJFE','DITYDI'),
('LENCU','DITYDI'),
('MEDSA','DITYDI'),
('MUSBO','DITYDI'),
('1NARG','DITYDI'),
('NIOTA','DITYDI'),
('GAOCA','DITYDI'),
('OTGUM','DITYDI'),
('PARCR','DITYDI'),
('POXDR','DITYDI'),
('POXPA','DITYDI'),
('PIBSX','DITYDI'),
('PUKSL','DITYDI'),
('CIXLU','DITYDI'),
('SLLSI','DITYDI'),
('SECCE','DITYDI'),
('SOLTU','DITYDI'),
('TRFPR','DITYDI'),
('TRFRE','DITYDI'),
('1TRZG','DITYDI'),
('TULHY','DITYDI'),
('VICFX','DITYDI'),
('ZEAMX','DITYDI'),
('1PIUG','TOUMPA'),
('CEUAT','THAUPI'),
('LAXDE','THAUPI'),
('PIUBR','THAUPI'),
('PIUCA','THAUPI'),
('PIUHA','THAUPI'),
('PIUNI','THAUPI'),
('PIUNL','THAUPI'),
('PIUPL','THAUPI'),
('PIUPN','THAUPI'),
('PIURA','THAUPI'),
('PIUSI','THAUPI'),
('OLVEU','PHILSU'),
('ACADA','XYLEFA'),
('ACASA','XYLEFA'),
('ACRPP','XYLEFA'),
('ACRRB','XYLEFA'),
('AMARE','XYLEFA'),
('AYLHE','XYLEFA'),
('ARTAO','XYLEFA'),
('ARTSS','XYLEFA'),
('ASPAC','XYLEFA'),
('CCOSS','XYLEFA'),
('CCOVI','XYLEFA'),
('CMIRA','XYLEFA'),
('CYAIL','XYLEFA'),
('1CTUG','XYLEFA'),
('CCSSI','XYLEFA'),
('CHEAL','XYLEFA'),
('CSTAL','XYLEFA'),
('CSTIC','XYLEFA'),
('CSTMO','XYLEFA'),
('CSTSA','XYLEFA'),
('CSTIS','XYLEFA'),
('1CJCG','XYLEFA'),
('1CIDG','XYLEFA'),
('CIDSI','XYLEFA'),
('1COFG','XYLEFA'),
('CONCN','XYLEFA'),
('CPMRE','XYLEFA'),
('CZRVL','XYLEFA'),
('CZRVG','XYLEFA'),
('1CYPF','XYLEFA'),
('SAOSC','XYLEFA'),
('CZSVI','XYLEFA'),
('OSPEK','XYLEFA'),
('OSPFR','XYLEFA'),
('DOSKA','XYLEFA'),
('DODVI','XYLEFA'),
('ELGAN','XYLEFA'),
('EMHMA','XYLEFA'),
('ERIBO','XYLEFA'),
('ERIKA','XYLEFA'),
('ERISS','XYLEFA'),
('ERISU','XYLEFA'),
('1ERYG','XYLEFA'),
('EPHCH','XYLEFA'),
('EPHTE','XYLEFA'),
('EYOCH','XYLEFA'),
('EYOPE','XYLEFA'),
('FIUCA','XYLEFA'),
('1FOLG','XYLEFA'),
('FRXAN','XYLEFA'),
('GENCO','XYLEFA'),
('GENEP','XYLEFA'),
('GENLU','XYLEFA'),
('GENSA','XYLEFA'),
('GLITR','XYLEFA'),
('GREJU','XYLEFA'),
('1HBEG','XYLEFA'),
('HBEEL','XYLEFA'),
('HECIT','XYLEFA'),
('HECSS','XYLEFA'),
('HECST','XYLEFA'),
('HEOEU','XYLEFA'),
('HIBSS','XYLEFA'),
('ILEAQ','XYLEFA'),
('IUGRE','XYLEFA'),
('LURNO','XYLEFA'),
('LAVAN','XYLEFA'),
('LAVDE','XYLEFA'),
('LAVLA','XYLEFA'),
('LAVST','XYLEFA'),
('LAVCY','XYLEFA'),
('LAVHE','XYLEFA'),
('LAVIN','XYLEFA'),
('LIGSI','XYLEFA'),
('LIQST','XYLEFA'),
('LONJA','XYLEFA'),
('MEDAR','XYLEFA'),
('MEDSA','XYLEFA'),
('MTDEX','XYLEFA'),
('MORAL','XYLEFA'),
('MORRU','XYLEFA'),
('MYMIN','XYLEFA'),
('MYVCO','XYLEFA'),
('NEROL','XYLEFA'),
('OLVEU','XYLEFA'),
('PELFR','XYLEFA'),
('PELGV','XYLEFA'),
('PEBAM','XYLEFA'),
('PGASA','XYLEFA'),
('PLRLA','XYLEFA'),
('PLMFR','XYLEFA'),
('PIAVE','XYLEFA'),
('PLTOC','XYLEFA'),
('1GRAF','XYLEFA'),
('POGMY','XYLEFA'),
('PMITR','XYLEFA'),
('PRNAN','XYLEFA'),
('PRNAR','XYLEFA'),
('PRNAV','XYLEFA'),
('PRNCF','XYLEFA'),
('PRNCE','XYLEFA'),
('PRNDO','XYLEFA'),
('PRNDU','XYLEFA'),
('PRNPS','XYLEFA'),
('PRNSC','XYLEFA'),
('PRNSO','XYLEFA'),
('QUEPA','XYLEFA'),
('QUERU','XYLEFA'),
('QUESU','XYLEFA'),
('QUESS','XYLEFA'),
('RHAAL','XYLEFA'),
('ROBPS','XYLEFA'),
('ROSCN','XYLEFA'),
('ROSXF','XYLEFA'),
('ROSMU','XYLEFA'),
('RMSOF','XYLEFA'),
('SNTCH','XYLEFA'),
('SORHA','XYLEFA'),
('SPUJU','XYLEFA'),
('STZRE','XYLEFA'),
('1SRQG','XYLEFA'),
('TEUCP','XYLEFA'),
('ULEEU','XYLEFA'),
('ULEMI','XYLEFA'),
('ULMAM','XYLEFA'),
('VACCO','XYLEFA'),
('VACDA','XYLEFA'),
('VACVG','XYLEFA'),
('1VING','XYLEFA'),
('VINMI','XYLEFA'),
('1VITG','XYLEFA'),
('VITLA','XYLEFA'),
('VITRI','XYLEFA'),
('VITVI','XYLEFA'),
('WESRO','XYLEFA'),
('WESGL','XYLEFA'),
('1GRAF','GRCPAT'),
('VITVI','GRCPAT'),
('1CIDG','HOMLTR'),
('CIDSI','HOMLTR'),
('1FRXG','HOMLTR'),
('LAEIN','HOMLTR'),
('MCDTE','HOMLTR'),
('MEDSA','HOMLTR'),
('NEROL','HOMLTR'),
('PEBAM','HOMLTR'),
('PRNDO','HOMLTR'),
('PRNDU','HOMLTR'),
('PRNPS','HOMLTR'),
('1RHUG','HOMLTR'),
('VITVI','HOMLTR'),
('IUGRE','CARHDI'),
('1CIDG','CRYBGN'),
('CIDLI','CRYBGN'),
('CIDPA','CRYBGN'),
('CIDRX','CRYBGN'),
('CIDSI','CRYBGN'),
('DOSKA','CRYBGN'),
('GOSHI','CRYBGN'),
('PEBAM','CRYBGN'),
('PUNGR','CRYBGN'),
('SOLME','CRYBGN'),
('VITVI','CRYBGN'),
('ZEAMX','CRYBGN'),
('AELMA','DIAACI'),
('AFQPA','DIAACI'),
('BZCLC','DIAACI'),
('1AYAG','DIAACI'),
('SEVBU','DIAACI'),
('BCUDA','DIAACI'),
('CSJED','DIAACI'),
('1CJCG','DIAACI'),
('CJCWE','DIAACI'),
('1CIDG','DIAACI'),
('CIDAY','DIAACI'),
('CIDAF','DIAACI'),
('CIDAU','DIAACI'),
('CIDAC','DIAACI'),
('CIDAL','DIAACI'),
('CIDHL','DIAACI'),
('CIDHA','DIAACI'),
('CIDHY','DIAACI'),
('CIDID','DIAACI'),
('CIDJA','DIAACI'),
('CIDLP','DIAACI'),
('CIDLT','DIAACI'),
('CIDLI','DIAACI'),
('CIDMA','DIAACI'),
('CIDGR','DIAACI'),
('CIDME','DIAACI'),
('CIDPA','DIAACI'),
('CIDRH','DIAACI'),
('CIDRE','DIAACI'),
('CIDSI','DIAACI'),
('CIDRA','DIAACI'),
('CIDTW','DIAACI'),
('CIDVO','DIAACI'),
('CIDWE','DIAACI'),
('CIDLO','DIAACI'),
('CIDNO','DIAACI'),
('CUSAO','DIAACI'),
('CUSEX','DIAACI'),
('CUSHA','DIAACI'),
('CUSIN','DIAACI'),
('CUSLA','DIAACI'),
('CRHMY','DIAACI'),
('EMCGL','DIAACI'),
('FIUCA','DIAACI'),
('1FOLG','DIAACI'),
('FOLJA','DIAACI'),
('FOLSS','DIAACI'),
('GLWPE','DIAACI'),
('FEOLI','DIAACI'),
('MEJCA','DIAACI'),
('MUYKO','DIAACI'),
('MUYPA','DIAACI'),
('PMITR','DIAACI'),
('1RUTF','DIAACI'),
('SWNGL','DIAACI'),
('TDDAS','DIAACI'),
('TPHTR','DIAACI'),
('VEPUN','DIAACI'),
('CJFMI','DIAACI'),
('CJFSS','DIAACI'),
('ZANAI','DIAACI'),
('PIUPI','MATSFE'),
('1ACAG','PLTPMU'),
('ACAMR','PLTPMU'),
('ACRNE','PLTPMU'),
('AILAL','PLTPMU'),
('ARUAN','PLTPMU'),
('MEIAD','PLTPMU'),
('BFDRI','PLTPMU'),
('CAEEC','PLTPMU'),
('CMUBR','PLTPMU'),
('KNXES','PLTPMU'),
('KNXLE','PLTPMU'),
('CSNSA','PLTPMU'),
('CSUCU','PLTPMU'),
('CEDFI','PLTPMU'),
('KNSPL','PLTPMU'),
('CZLTO','PLTPMU'),
('1CIDG','PLTPMU'),
('CYLAV','PLTPMU'),
('CVNFL','PLTPMU'),
('CVNPI','PLTPMU'),
('DEXRE','PLTPMU'),
('DOSKA','PLTPMU'),
('ENECO','PLTPMU'),
('ERZCG','PLTPMU'),
('1EUCG','PLTPMU'),
('EUCCM','PLTPMU'),
('EUCDU','PLTPMU'),
('EUCRO','PLTPMU'),
('EUCTR','PLTPMU'),
('EUCUP','PLTPMU'),
('EUCVI','PLTPMU'),
('FIUBE','PLTPMU'),
('FIUCA','PLTPMU'),
('1FRXG','PLTPMU'),
('FRXEX','PLTPMU'),
('GRERO','PLTPMU'),
('IUGRE','PLTPMU'),
('LURNO','PLTPMU'),
('LIGLU','PLTPMU'),
('LIQST','PLTPMU'),
('LIVCH','PLTPMU'),
('LUHDI','PLTPMU'),
('LUEGU','PLTPMU'),
('MCJST','PLTPMU'),
('MAGGR','PLTPMU'),
('1MABG','PLTPMU'),
('MABSD','PLTPMU'),
('MABSY','PLTPMU'),
('MNGIN','PLTPMU'),
('1MORUG','PLTPMU'),
('PCJAQ','PLTPMU'),
('PEBAM','PLTPMU'),
('1PIUG','PLTPMU'),
('PITGO','PLTPMU'),
('PTUUN','PLTPMU'),
('PLTHY','PLTPMU'),
('PLYEL','PLTPMU'),
('1POPG','PLTPMU'),
('POPAL','PLTPMU'),
('POPDE','PLTPMU'),
('POPNI','PLTPMU'),
('POPCA','PLTPMU'),
('PRNAR','PLTPMU'),
('PRNAV','PLTPMU'),
('PRNDO','PLTPMU'),
('PRNPS','PLTPMU'),
('1PYUG','PLTPMU'),
('PYUCO','PLTPMU'),
('1QUEG','PLTPMU'),
('QUEPA','PLTPMU'),
('QUERO','PLTPMU'),
('QUERU','PLTPMU'),
('1ROBG','PLTPMU'),
('ROBPS','PLTPMU'),
('1SAXG','PLTPMU'),
('SAXAL','PLTPMU'),
('SAXBA','PLTPMU'),
('SAXNI','PLTPMU'),
('SZBPA','PLTPMU'),
('SEICM','PLTPMU'),
('TADDI','PLTPMU'),
('TILMO','PLTPMU'),
('1ULMG','PLTPMU'),
('ULMPU','PLTPMU'),
('VIXME','PLTPMU');
INSERT INTO simfito.changelog (changelog)
VALUES 
('<div>
    <h3>MODIFICA TIPOLOGIA DI SITO</h3>
    <p>&Egrave; possibile modificare la “tipologia di sito” di un sito esistente attraverso la schermata “Nuova scheda”.</p>
    <p>Si specifica che la modifica &egrave; temporanea e strettamente legata all&apos;attivit&agrave; svolta ed archiviata nella scheda creata, 
        che potr&agrave; essere duplicata per trascinare la modifica apportata. Si sottolinea che questa <b>MODIFICA TIPOLOGIA DI SITO</b>b> non cambier&agrave; 
        la tipologia di sito associata durante la creazione del sito stesso.</p>
</div>'),
('<div>
    <h3>Revisione del calcolo del “Tempo residuo”</h3>
    <p>Nel calcolo del tempo residuo verr&agrave; ora tenuto conto automaticamente delle attivit&agrave; svolte dal tecnico in quella giornata relativamente alla gestione delle trappole, 
        in particolare “Posizionamento” e “Rimozione”.</p>
</div>'),
('<div>
    <h3>Modifica campi nelle osservazioni</h3>
    <p>&Egrave; stato implementato il form delle osservazioni per permettere l&apso;adeguamento dei dati tecnici richiesti a livello nazionale e comunitario.</p>
    <p>La compilazione dei diversi campi varier&agrave; a seconda dell&apos; organismo nocivo controllato, della tipologia controllata e della tipologia di sito.</p> 
    <p>Il manuale di inserimento è fornito a tutti gli Utenti tramite trasmissione all’indirizzo elettronico.</p>
</div>'),
('<div>
    <h3>Strumento per la ricerca delle trappole</h3>
    <p>La schermata “Gestione trappole” &egrave; stata implementata con uno strumento che permette di ricercare tutte le trappole presenti in un cerchio individuato dall&apos;Utente, 
        successivamente all’inserimento di coordinate per il centro ed il raggio richiesto.</b>
    <p>Sar&apos; anche possibile scegliere se visualizzare tutte le trappole presenti o solo quelle riferite ad un determinato organismo nocivo.</p>
</div>');
UPDATE simfito.tecnici set "read"=false;